### ISSUE TITLE
Graph support

### ISSUE THREAD

**Issue by dibg** [s00500/ESPUI#10]
I just discover your incredible library! It was something was well needed. The thing that surprise me the most is that you make it easy to use. This definitely will empower kids and hobbyist alike to be more creative with their projects.  One enchantment i can think of is the the support for graphs. It make tremendous sense since most hobby projects is about collect and visualize data. Whether station, garden monitor, temperature monitor, air quality sensor and the list going on. The fact that everything can be self contain with out a external server make it ideal for spread adoption.

**Comment by s00500** [comment]
hm alright, that is a difficult one... we would have to think about where the data for the graph is stored and how it is sent out initially, or if we do not send it out at all and just visualize it in the front end.... anyway. input definitely wanted here!

**Comment by dibg** [comment]
The simplest way to do it is to send the graph data in real time. So no storage, just plotting what ever comes while the ui is open. That's the quickest way which still provide useful functionality. A example use of this will be a poor's man oscilloscope or live visualization telemetry of a rc car/boat/drone. Now that is the important part to be implemented. A graph with the option to receive data, plot multiple axis, set axis limits, and clear graph data. If that is in place then people can use that to send previously stored data and therefore make possible projects like garden/temperature/air monitor.

**Comment by s00500** [comment]
hm ok yeah I like the idea, I'll see what I can do, right now I am unfortunately in a time planning deadlock, but in case anyone wants to have a try I am much quicker in reviewing pull requests :-)

**Comment by s00500** [comment]
what do you think of something like this?
https://codepen.io/meloncholy/pen/KxiJA

**Comment by s00500** [comment]
Also a nice design: https://codepen.io/deep1808/pen/yNQGZe

**Comment by s00500** [comment]
An additional id could be storing the values of the graph in local storage in the browser, not ideal but simple, what do you think?

**Comment by s00500** [comment]
Ok so I forked one of the graphs...
https://codepen.io/s00500/pen/LXBZJJ

First I would also like to add the circle diagram since it looks nice

Second there are still issues here since this thin depends on jquery (we should be able to use our zeptoJS though)
and worse on [snap svg](https://cdnjs.cloudflare.com/ajax/libs/snap.svg/0.3.0/snap.svg-min.js)

So we will need to get rid of the dependencies for it to work and we need to make it as small as possible....

@orithena Do you want to help here? :-)

**Comment by orithena** [comment]
I'm intrigued to try my hand at implementing it in zepto and vanillaJS... no guarantees as to when, though ^^

**Comment by s00500** [comment]
Great =D, I will make sure the rest is ready by then ;-)

**Comment by s00500** [comment]
ok this is going to be it for now
https://codepen.io/s00500/pen/zXEZYX

somebody can play with the styling more if you want =D

**Comment by s00500** [comment]
will be released in 2.0
