### ISSUE TITLE
clearGraph is doing nothing

### ISSUE THREAD

**Issue by dervomsee** [s00500/ESPUI#101]
Hi,
i try to clear a graph by calling the clearGraph function in the callback function of a button, but nothing happens.
The function behind is empty in the sourcecode. 
https://github.com/s00500/ESPUI/blob/482768863514b59b4b958c9a481b4523c1818368/src/ESPUI.cpp#L892
How can i clear a graph?

**Comment by s00500** [comment]
this functionality is not implemented, right now you would need to clear your browsers localstorage to clear a graph

**Comment by test3210-d** [comment]
ESPUI.clearGraph(graphId);
ESPUI.updateControl(graphId);

clear for me

**Comment by Andy1978** [comment]
I think this was implemented with https://github.com/s00500/ESPUI/commit/f35d3a19d42fa16cc04e66a9dc5bd08b1ff265b5 and can be closed
