### ISSUE TITLE
Feedback when pressing a button

### ISSUE THREAD

**Issue by kbssa** [s00500/ESPUI#110]
I would like to add feedback when pressing a button. 

Is that possible ?

Thank you for the awesome library

**Comment by s00500** [comment]
Definitely, what kind of feedback do you think of ?

This repo is open for PRs, but I wont have time for working on it myself

**Comment by kbssa** [comment]
I thought of something like change the the button color when pressing down.

The buttons are static and because of that I don't know if the button was really touched or not.

 Hope you understood in  what I thought.

**Comment by iangray001** [comment]
There are a lot of ways to achieve this. I simply added the following to `style.css`.

```
button:active {
  background-color: #666666;
  transform: translateX(4px) translateY(4px);
}
```

Much more fancy CSS transitions are available but this works on basically anything and provides sufficient feedback to show that a button has been pressed.

**Comment by s00500** [comment]
Sounds like a nice addition, it is now merged with your PR :-) So I guess we can close this

**Comment by thomastech** [comment]
@iangray001, Thank you for adding this. Button presses look much better.

It would be great to have a similar solution for the Pad control. Any chance you can do your magic on it?

- Thomas
