### ISSUE TITLE
ESP8266 (ESP12-F) crashing

### ISSUE THREAD

**Issue by kbssa** [s00500/ESPUI#111]
If modify a little the tabbedGui example to change the button color the ESP resets every time I press the button.

void buttonCallback(Control* sender, int type) {
	switch (type) {
	case B_DOWN:
		Serial.println("Button DOWN");
		ESPUI.getControl(button1)->color = ControlColor::Carrot;
		ESPUI.updateControl(button1);

		break;

	case B_UP:
		Serial.println("Button UP");
		ESPUI.getControl(button1)->color = ControlColor::Wetasphalt;
		ESPUI.updateControl(button1);
		break;
	}
}

This is a bug or I miss something ?

**Comment by kbssa** [comment]
Here it is

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

Exception (3):
epc1=0x40100689 epc2=0x00000000 epc3=0x00000000 excvaddr=0x40003b70 depc=0x00000000

>>>stack>>>

ctx: sys
sp: 3fffea00 end: 3fffffb0 offset: 0190
3fffeb90:  00000000 00000002 3fffebe0 3fffece8  
3fffeba0:  00002460 0000048c 0000048c 4010078b  
3fffebb0:  00000002 3fff17c4 00000002 00000001  
3fffebc0:  00000000 0000002e 00000020 40100a0f  
3fffebd0:  00000000 3fffecd4 0000002e 00000001  
3fffebe0:  00000000 0000002e 3fff17c4 4020b01b  
3fffebf0:  00000000 3a226575 65725022 2c227373  
3fffec00:  3fff1dc4 00000001 00000001 3fff1e34  
3fffec10:  00000002 40208300 3fff2004 3fffece8  
3fffec20:  00002428 4020b215 00000000 0000002e  
3fffec30:  3fff17c4 0000002e 3fff1dfc 4020b1c7  
3fffec40:  3fff0ef4 4020bc7c 00000000 3fffece8  
3fffec50:  3fff1fac 3fff1dfc 3fff1f84 4020bb5d  
3fffec60:  00000000 3fff1dfc 3fff1f84 4020bbee  
3fffec70:  3fff0ef4 3fff1f84 3fff1dfc 4020bc8e  
3fffec80:  3fff1dac 3fffece8 00000005 3fffecd4  
3fffec90:  3fff157c 3fff1dac 3fff15ec 4020bcc5  
3fffeca0:  3fff157c 3fff0ef4 3fff0ef4 4020bcf6  
3fffecb0:  00000005 3fffecd4 3fffecf4 4020bd26  
3fffecc0:  00000005 3fffecd4 3ffef150 402090d3  
3fffecd0:  4010249c 3fff2004 3fff200a 3fff2794  
3fffece0:  3fff27d4 3fff2800 3fff27c4 3fff2794  
3fffecf0:  3ffe8da0 3fff157c 002e002f 00213fdd  
3fffed00:  3fffece8 3fffecd4 3fffed50 0000000b  
3fffed10:  ffffffff 3fff27a4 0000000b 402130b4  
3fffed20:  402130a8 3ffef394 3ffe8dc2 0000000b  
3fffed30:  3ffef150 0000000b 3ffef150 4020915e  
3fffed40:  ffffffff 3ffef150 3ffef394 40213664  
3fffed50:  776f6400 3ffef0cc ffffffff 402055b0  
3fffed60:  3fff1f84 3ffef150 3fff0b9c 402093fc  
3fffed70:  00003100 4bc6a7f0 80353f7c 776f6462  
3fffed80:  31313a6e 88000000 4bc6a7f0 00000000  
3fffed90:  40100ca2 00000000 401002a8 3fff1f84  
3fffeda0:  3fff17a8 3fff1f84 00000004 40215e0a  
3fffedb0:  00671d2d 3ffefb0c 3ffead90 40216071  
3fffedc0:  00000008 4bc6a7f0 f916872b 3fff1f84  
3fffedd0:  3fff17a2 00000008 00000008 4020c069  
3fffede0:  40230c40 3fffee80 401002a8 0000592d  
3fffedf0:  3fff17b0 000000be 3fffee80 4021e949  
3fffee00:  00671d28 5f4b4e49 45323234 3fff175c  
3fffee10:  00000000 3fffee60 3fff17c4 4020c095  
3fffee20:  00000000 3fffee60 3fff17c4 4020a1ee  
3fffee30:  3fff1664 00890260 3ffefb24 00000000  
3fffee40:  3ffe0000 3ffefb24 00000000 3fff1664  
3fffee50:  3fff175c 00000000 3fff17c4 4020a396  
3fffee60:  3fff1724 3fff15fc 4023b507 3ffef748  
3fffee70:  3ffef8b8 3ffef968 3fff175c 3ffef748  
3fffee80:  3fff1664 3ffef72c 3ffef72d 4022251c  
3fffee90:  00001d88 00000000 00000020 40100a44  
3fffeea0:  3ffef8b8 7700a8c0 000004b3 3fff02f4  
3fffeeb0:  00000000 00000000 00000020 3ffef968  
3fffeec0:  3ffef8b8 3fff177a 3fff175c 40227fe6  
3fffeed0:  00000014 3ffef8b8 00000044 3fff02f4  
3fffeee0:  00000000 3fff029c 00000020 40100a0f  
3fffeef0:  4023a780 3fff157c 3fff029c 3fff02f4  
3fffef00:  00000008 3ffef8b8 3fff175c 4021f0c9  
3fffef10:  3fffdc80 3fff029c 3fff157c 4021eee8  
3fffef20:  4023f4ba 3fff029c 3fff157c 4023f4cb  
3fffef30:  3fff176c 3fff175c 00000000 3ffe8524  
3fffef40:  4023a3ab 00000000 3fff157c 40241287  
3fffef50:  40000f49 3fffdab0 3fffdab0 40000f49  
3fffef60:  40000e19 00000005 0005de4c 00000000  
3fffef70:  00000000 aa55aa55 000000d3 401048d5  
3fffef80:  401048db 0005de4c 00000000 da8dc0ac  
3fffef90:  4010000d b693abb1 f5863964 a346df87  
3fffefa0:  00000000 3fffef3c 00000000 3fffff38  
3fffefb0:  3fffffc0 00000000 00000000 feefeffe  
3fffefc0:  feefeffe feefeffe feefeffe feefeffe  
3fffefd0:  feefeffe feefeffe feefeffe feefeffe  
3fffefe0:  feefeffe feefeffe feefeffe feefeffe  
3fffeff0:  feefeffe feefeffe feefeffe feefeffe  
3ffff000:  feefeffe feefeffe feefeffe feefeffe  
3ffff010:  feefeffe feefeffe feefeffe feefeffe  
3ffff020:  feefeffe feefeffe feefeffe feefeffe  
3ffff030:  feefeffe feefeffe feefeffe feefeffe  
3ffff040:  feefeffe feefeffe feefeffe feefeffe  
3ffff050:  feefeffe feefeffe feefeffe feefeffe  
3ffff060:  feefeffe feefeffe feefeffe feefeffe  
3ffff070:  feefeffe feefeffe feefeffe feefeffe  
3ffff080:  feefeffe feefeffe feefeffe feefeffe  
3ffff090:  feefeffe feefeffe feefeffe feefeffe  
3ffff0a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff0f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff100:  feefeffe feefeffe feefeffe feefeffe  
3ffff110:  feefeffe feefeffe feefeffe feefeffe  
3ffff120:  feefeffe feefeffe feefeffe feefeffe  
3ffff130:  feefeffe feefeffe feefeffe feefeffe  
3ffff140:  feefeffe feefeffe feefeffe feefeffe  
3ffff150:  feefeffe feefeffe feefeffe feefeffe  
3ffff160:  feefeffe feefeffe feefeffe feefeffe  
3ffff170:  feefeffe feefeffe feefeffe feefeffe  
3ffff180:  feefeffe feefeffe feefeffe feefeffe  
3ffff190:  feefeffe feefeffe feefeffe feefeffe  
3ffff1a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff1f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff200:  feefeffe feefeffe feefeffe feefeffe  
3ffff210:  feefeffe feefeffe feefeffe feefeffe  
3ffff220:  feefeffe feefeffe feefeffe feefeffe  
3ffff230:  feefeffe feefeffe feefeffe feefeffe  
3ffff240:  feefeffe feefeffe feefeffe feefeffe  
3ffff250:  feefeffe feefeffe feefeffe feefeffe  
3ffff260:  feefeffe feefeffe feefeffe feefeffe  
3ffff270:  feefeffe feefeffe feefeffe feefeffe  
3ffff280:  feefeffe feefeffe feefeffe feefeffe  
3ffff290:  feefeffe feefeffe feefeffe feefeffe  
3ffff2a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff2f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff300:  feefeffe feefeffe feefeffe feefeffe  
3ffff310:  feefeffe feefeffe feefeffe feefeffe  
3ffff320:  feefeffe feefeffe feefeffe feefeffe  
3ffff330:  feefeffe feefeffe feefeffe feefeffe  
3ffff340:  feefeffe feefeffe feefeffe feefeffe  
3ffff350:  feefeffe feefeffe feefeffe feefeffe  
3ffff360:  feefeffe feefeffe feefeffe feefeffe  
3ffff370:  feefeffe feefeffe feefeffe feefeffe  
3ffff380:  feefeffe feefeffe feefeffe feefeffe  
3ffff390:  feefeffe feefeffe feefeffe feefeffe  
3ffff3a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff3f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff400:  feefeffe feefeffe feefeffe feefeffe  
3ffff410:  feefeffe feefeffe feefeffe feefeffe  
3ffff420:  feefeffe feefeffe feefeffe feefeffe  
3ffff430:  feefeffe feefeffe feefeffe feefeffe  
3ffff440:  feefeffe feefeffe feefeffe feefeffe  
3ffff450:  feefeffe feefeffe feefeffe feefeffe  
3ffff460:  feefeffe feefeffe feefeffe feefeffe  
3ffff470:  feefeffe feefeffe feefeffe feefeffe  
3ffff480:  feefeffe feefeffe feefeffe feefeffe  
3ffff490:  feefeffe feefeffe feefeffe feefeffe  
3ffff4a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff4f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff500:  feefeffe feefeffe feefeffe feefeffe  
3ffff510:  feefeffe feefeffe feefeffe feefeffe  
3ffff520:  feefeffe feefeffe feefeffe feefeffe  
3ffff530:  feefeffe feefeffe feefeffe feefeffe  
3ffff540:  feefeffe feefeffe feefeffe feefeffe  
3ffff550:  feefeffe feefeffe feefeffe feefeffe  
3ffff560:  feefeffe feefeffe feefeffe feefeffe  
3ffff570:  feefeffe feefeffe feefeffe feefeffe  
3ffff580:  feefeffe feefeffe feefeffe feefeffe  
3ffff590:  feefeffe feefeffe feefeffe feefeffe  
3ffff5a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff5f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff600:  feefeffe feefeffe feefeffe feefeffe  
3ffff610:  feefeffe feefeffe feefeffe feefeffe  
3ffff620:  feefeffe feefeffe feefeffe feefeffe  
3ffff630:  feefeffe feefeffe feefeffe feefeffe  
3ffff640:  feefeffe feefeffe feefeffe feefeffe  
3ffff650:  feefeffe feefeffe feefeffe feefeffe  
3ffff660:  feefeffe feefeffe feefeffe feefeffe  
3ffff670:  feefeffe feefeffe feefeffe feefeffe  
3ffff680:  feefeffe feefeffe feefeffe feefeffe  
3ffff690:  feefeffe feefeffe feefeffe feefeffe  
3ffff6a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff6f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff700:  feefeffe feefeffe feefeffe feefeffe  
3ffff710:  feefeffe feefeffe feefeffe feefeffe  
3ffff720:  feefeffe feefeffe feefeffe feefeffe  
3ffff730:  feefeffe feefeffe feefeffe feefeffe  
3ffff740:  feefeffe feefeffe feefeffe feefeffe  
3ffff750:  feefeffe feefeffe feefeffe feefeffe  
3ffff760:  feefeffe feefeffe feefeffe feefeffe  
3ffff770:  feefeffe feefeffe feefeffe feefeffe  
3ffff780:  feefeffe feefeffe feefeffe feefeffe  
3ffff790:  feefeffe feefeffe feefeffe feefeffe  
3ffff7a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff7f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff800:  feefeffe feefeffe feefeffe feefeffe  
3ffff810:  feefeffe feefeffe feefeffe feefeffe  
3ffff820:  feefeffe feefeffe feefeffe feefeffe  
3ffff830:  feefeffe feefeffe feefeffe feefeffe  
3ffff840:  feefeffe feefeffe feefeffe feefeffe  
3ffff850:  feefeffe feefeffe feefeffe feefeffe  
3ffff860:  feefeffe feefeffe feefeffe feefeffe  
3ffff870:  feefeffe feefeffe feefeffe feefeffe  
3ffff880:  feefeffe feefeffe feefeffe feefeffe  
3ffff890:  feefeffe feefeffe feefeffe feefeffe  
3ffff8a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff8f0:  feefeffe feefeffe feefeffe feefeffe  
3ffff900:  feefeffe feefeffe feefeffe feefeffe  
3ffff910:  feefeffe feefeffe feefeffe feefeffe  
3ffff920:  feefeffe feefeffe feefeffe feefeffe  
3ffff930:  feefeffe feefeffe feefeffe feefeffe  
3ffff940:  feefeffe feefeffe feefeffe feefeffe  
3ffff950:  feefeffe feefeffe feefeffe feefeffe  
3ffff960:  feefeffe feefeffe feefeffe feefeffe  
3ffff970:  feefeffe feefeffe feefeffe feefeffe  
3ffff980:  feefeffe feefeffe feefeffe feefeffe  
3ffff990:  feefeffe feefeffe feefeffe feefeffe  
3ffff9a0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9b0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9c0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9d0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9e0:  feefeffe feefeffe feefeffe feefeffe  
3ffff9f0:  feefeffe feefeffe feefeffe feefeffe  
3ffffa00:  feefeffe feefeffe feefeffe feefeffe  
3ffffa10:  feefeffe feefeffe feefeffe feefeffe  
3ffffa20:  feefeffe feefeffe feefeffe feefeffe  
3ffffa30:  feefeffe feefeffe feefeffe feefeffe  
3ffffa40:  feefeffe feefeffe feefeffe feefeffe  
3ffffa50:  feefeffe feefeffe feefeffe feefeffe  
3ffffa60:  feefeffe feefeffe feefeffe feefeffe  
3ffffa70:  feefeffe feefeffe feefeffe feefeffe  
3ffffa80:  feefeffe feefeffe feefeffe feefeffe  
3ffffa90:  feefeffe feefeffe feefeffe feefeffe  
3ffffaa0:  feefeffe feefeffe feefeffe feefeffe  
3ffffab0:  feefeffe feefeffe feefeffe feefeffe  
3ffffac0:  feefeffe feefeffe feefeffe feefeffe  
3ffffad0:  feefeffe feefeffe feefeffe feefeffe  
3ffffae0:  feefeffe feefeffe feefeffe feefeffe  
3ffffaf0:  feefeffe feefeffe feefeffe feefeffe  
3ffffb00:  feefeffe feefeffe feefeffe feefeffe  
3ffffb10:  feefeffe feefeffe feefeffe feefeffe  
3ffffb20:  feefeffe feefeffe feefeffe feefeffe  
3ffffb30:  feefeffe feefeffe feefeffe feefeffe  
3ffffb40:  feefeffe feefeffe feefeffe feefeffe  
3ffffb50:  feefeffe feefeffe feefeffe feefeffe  
3ffffb60:  00000005 00000000 00000020 401001fc  
3ffffb70:  feefeffe feefeffe 00000005 40101540  
3ffffb80:  3ffe97c5 401047ef 3ffed200 feefeffe  
3ffffb90:  401020db 3ffed200 feefeffe feefeffe  
3ffffba0:  fffffffa 00015a51 4023b507 00000001  
3ffffbb0:  ffffffff 00000000 3ffe9911 00000008  
3ffffbc0:  4023b556 3ffecf58 3ffefb0c 00000001  
3ffffbd0:  00000002 00000000 00000020 401001fc  
3ffffbe0:  00000005 00000005 00000002 40101540  
3ffffbf0:  3ffe97c2 4023a613 3ffecf58 00000020  
3ffffc00:  00000000 4022dbc7 3ffee3e8 3ffefb0c  
3ffffc10:  00000000 00000002 00000000 3ffecf58  
3ffffc20:  3fff2812 40104e1b 3fff0d1c 3ffef504  
3ffffc30:  3fff029c 3fffc718 3ffffd20 00000000  
3ffffc40:  3ffef4d0 4021eaa9 3fff0d1c 3ffef504  
3ffffc50:  0000ffff 00042035 00002035 003fd000  
3ffffc60:  40254ab0 0000049c 00000000 00000000  
3ffffc70:  3ffef8f0 3ffef8b8 3fff27dc 4021ed36  
3ffffc80:  4010249c 3ffef8b8 3fff27dc 4021f154  
3ffffc90:  3ffef780 00000030 00000016 00000000  
3ffffca0:  0000001f 00000020 3fffff14 3ffef784  
3ffffcb0:  3ffef8f0 00000000 3ffef8b8 40226804  
3ffffcc0:  0000000b 00000000 3ffe9911 00000008  
3ffffcd0:  00000000 3fff27dc 0000048b 4010078b  
3ffffce0:  000023d8 0000001f 3fffff14 3fff27dc  
3ffffcf0:  3fff27dc 3fff1668 3ffef8b8 40226a58  
3ffffd00:  3fff0000 00000000 00000020 40100a44  
3ffffd10:  3fff2820 3fff1668 3ffef8b8 40228248  
3ffffd20:  00000610 0000005a 00000000 40228d40  
3ffffd30:  00000014 3fff1664 000000ff 00000000  
3ffffd40:  00000006 3ffef874 000005b4 4021f1e8  
3ffffd50:  00000005 00000000 00000020 401001fc  
3ffffd60:  3fff1dac 3ffef8b8 00000005 40101540  
3ffffd70:  3ffe97c5 401047ef 3ffed200 401001fc  
3ffffd80:  401020db 3ffed200 3ffed940 40101540  
3ffffd90:  fffffff9 015827b4 3ffedc20 401022b8  
3ffffda0:  00000005 00000000 00000020 401001fc  
3ffffdb0:  401036e7 00040000 00000000 00040000  
3ffffdc0:  00000000 401036e4 00040000 401001fc  
3ffffdd0:  3ffed940 4010264b 00000000 00040000  
3ffffde0:  00000000 00000000 00000020 401001fc  
3ffffdf0:  3ffea058 2c9f0300 00000000 40101540  
3ffffe00:  00000005 00000000 00000020 401001fc  
3ffffe10:  00000001 401039b2 00000005 40101540  
3ffffe20:  3ffe97c5 401047ef 3ffed200 00000000  
3ffffe30:  401020db 3ffed200 0000001f 401001fc  
3ffffe40:  00007fff 015c5906 3ffedc20 401022b8  
3ffffe50:  3ffea064 00000000 00000000 00000030  
3ffffe60:  00007fff 015c5906 4010277a 00000100  
3ffffe70:  3ffea064 7fffffff 00000000 00000001  
3ffffe80:  00000001 00004288 00000000 fffffffe  
3ffffe90:  3ffea064 3fffc6fc 00000001 015c5906  
3ffffea0:  3ffea070 2c9f0300 4000050c 3fffc278  
3ffffeb0:  4010249c 3fffc200 00000022 00000000  
3ffffec0:  40100cd5 00000030 00000010 ffffffff  
3ffffed0:  40100cd5 00000000 00000001 00000001  
3ffffee0:  3fffdab0 00000000 3fffd9d0 3ffef2fc  
3ffffef0:  00000000 00000000 00000001 3ffe8524  
3fffff00:  00000000 3fffdad0 3ffef2fc 00000030  
3fffff10:  007a1220 3fff1700 002a002f 802109a9  
3fffff20:  00000000 4bc6a7f0 5e76c8b4 00000000  
3fffff30:  00000000 00000000 4bc6a7f0 00000000  
3fffff40:  3fffff90 3fffff90 401002a8 0000592d  
3fffff50:  00000000 3ffef150 3fff0d5c 40209191  
3fffff60:  007a1200 71102dc5 00000000 402076c4  
3fffff70:  00000000 00000000 3ffef2bc 3ffef2fc  
3fffff80:  00000000 00000000 00000001 401001fc  
3fffff90:  3fffdad0 00000000 3ffef2bc 4010021d  
3fffffa0:  3fffdad0 00000000 3ffef2bc 4021222d  
<<<stack<<<

--------------- CUT HERE FOR EXCEPTION DECODER ---------------

 ets Jan  8 2013,rst cause:4, boot mode:(3,6)

wdt reset
load 0x4010f000, len 3584, room 16 
tail 0
chksum 0xb0
csum 0xb0
v2843a5ac
~ld

**Comment by s00500** [comment]
Ok, can you try to use the ESP Exception decoder either in the Arduino IDE or in the platformIO monitor to decode it ?

**Comment by kbssa** [comment]
This is the Exception decoder log.

```
Exception 28: LoadProhibited: A load referenced a page mapped with an attribute that does not permit loads
PC: 0x40220ca7: tcp_free_acked_segments at core/tcp_in.c line 1101
EXCVADDR: 0x08600805

Decoding stack results
0x40100274: ets_post(uint8, ETSSignal, ETSParam) at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 177
0x40220ecc: tcp_receive at core/tcp_in.c line 1294
0x4022216a: tcp_input at core/tcp_in.c line 983
0x40100ab8: malloc(size_t) at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\umm_malloc\umm_malloc.cpp line 552
0x40227ed2: ip4_input at core/ipv4/ip4.c line 1467
0x40100a83: free(void*) at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\umm_malloc\umm_malloc.cpp line 398
0x4021eff9: ethernet_input_LWIP2 at netif/ethernet.c line 188
0x4021ee18: esp2glue_ethernet_input at glue-lwip/lwip-git.c line 469
0x4023f3e2: ethernet_input at glue-esp/lwip-esp.c line 365
0x4023f3f3: ethernet_input at glue-esp/lwip-esp.c line 373
0x40100274: ets_post(uint8, ETSSignal, ETSParam) at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 177
0x40100274: ets_post(uint8, ETSSignal, ETSParam) at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 177
0x4021e9d9: glue2esp_linkoutput at glue-esp/lwip-esp.c line 301
0x4021ec66: new_linkoutput at glue-lwip/lwip-git.c line 260
0x4021f084: ethernet_output at netif/ethernet.c line 312
0x402266f0: etharp_output_to_arp_index at core/ipv4/etharp.c line 770
0x401007ff: umm_free_core(void*) at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\umm_malloc\umm_malloc.cpp line 351
0x40226944: etharp_output_LWIP2 at core/ipv4/etharp.c line 885
0x40100ab8: malloc(size_t) at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\umm_malloc\umm_malloc.cpp line 552
0x40228134: ip4_output_if_opt_src at core/ipv4/ip4.c line 1764
0x40228c2c: mem_malloc at core/mem.c line 210
0x40100274: ets_post(uint8, ETSSignal, ETSParam) at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 177
0x40100274: ets_post(uint8, ETSSignal, ETSParam) at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 177
0x40100274: ets_post(uint8, ETSSignal, ETSParam) at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 177
0x40100274: ets_post(uint8, ETSSignal, ETSParam) at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 177
0x402129a4: run_scheduled_functions() at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/PolledTimeout.h line 192
0x40214011: __loop_end() at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 184
0x4010036c: millis() at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_wiring.cpp line 188
0x40209121: ESPUIClass::updateControlValue(Control*, String const&, int) at C:\Users\SuporteProduto1\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp line 832
0x40207654: WiFiUDP::parsePacket() at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\ESP8266WiFi\src\WiFiUdp.cpp line 199
0x40100274: ets_post(uint8, ETSSignal, ETSParam) at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 177
0x40100295: esp_schedule() at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 125
0x4021404d: loop_wrapper() at C:\Users\SuporteProduto1\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\core_esp8266_main.cpp line 199
```
![image](https://user-images.githubusercontent.com/5925493/106593776-fe584c80-652f-11eb-8b30-e60373d9da73.png)

I am trying to change the button label on the fly, but always that I try it the the controls don't get loaded and the page disconnects as soon as I refresh it.

Is that possible to achieve that or the library only accecpts hardcoded labels ?

Thank you in advance.

**Comment by iangray001** [comment]
Closing this because even if the issue causing the crash was resolved, this wouldn't update the colour of the panel as desired. To change panel colours dynamically you can now use the recently added Inline Styles (in the README).
