### ISSUE TITLE
How to use prepare_static_ui_sources.py

### ISSUE THREAD

**Issue by kbssa** [s00500/ESPUI#112]
Someone could teach me how to use the prepare_static_ui_sources.py script 

I need to make some changes in the CSS style to make the button change the color when I press it down, but I don't know how to
use the python script.

**Comment by nodoubtman** [comment]
prepare_static_ui_sources.py -a

**Comment by kbssa** [comment]
Where I execute this command ? Cmd or I need to install python ? 

Sorry, but I have no knowledge about python

**Comment by kbssa** [comment]
When I try to execute the command above I get the error below

`    from jsmin import jsmin as jsminify
ModuleNotFoundError: No module named 'jsmin'`

**Comment by nodoubtman** [comment]
You have to install the module . Google it.
