### ISSUE TITLE
How to create a button without hardcoded label ?

### ISSUE THREAD

**Issue by kbssa** [s00500/ESPUI#113]
I am trying to create a button with the label name from a variable, but without success.

```
String buttonName = "Push Button";
buttonName += 1;

ESPUI.button(buttonName.c_str(), &buttonCallback, ControlColor::Peterriver, "Press");
```

What is the right way of doing that ?

Thanks

**Comment by s00500** [comment]
What is the intent behind this ? 
The problem is that the label must be a const char*, .c_str() will only give you a char pointer and if you later change it it might break things and cause crashes

**Comment by robvoi** [comment]
Would like to get the same thing done. Either change the description of the button or the button label.
The intent is do visualize the a status without an extra label object. (preferences saved/unsaved) 

Any idea on how to do this?

**Comment by kbssa** [comment]
Yes, l have the same needs as @robvoi. I need to create a lot of buttons dynamically for a home automation system with the option to change names of them when needed.

Should the library be changed to achieve that ?

**Comment by christo** [comment]
Not sure if this is considered a different issue, but I would like a button without a label. If my need is different, then the description of this issue should potentially be "How to create a button with dynamic label".

**Comment by nodoubtman** [comment]
> 



> I am trying to create a button with the label name from a variable, but without success.
> 
> ```
> String buttonName = "Push Button";
> buttonName += 1;
> 
> ESPUI.button(buttonName.c_str(), &buttonCallback, ControlColor::Peterriver, "Press");
> ```
> 
> What is the right way of doing that ?
> 
> Thanks

You can do that: 

 String buttonName = "Push Button";
++counter;
buttonName += String(counter);

char bufferButton[buttonName.length()+1 + 5];
buttonName.toCharArray( bufferButton, sizeof(bufferButton[) );
ESPUI.button(bufferButton, &buttonCallback, ControlColor::Peterriver, "Press");

Voilà! :)

Bonne chance :)
Marc.

**Comment by thomastech** [comment]
The simplest solution is to declare the String as a static type. For example:
```
static String buttonName = "Push Button";
buttonName += 1;
ESPUI.button(buttonName.c_str(), &buttonCallback, ControlColor::Peterriver, "Press");
```
An explanation why this is necessary is discussed in issue #98.

- Thomas

**Comment by s00500** [comment]
Yep this is one way, the other would be just declaring on the heap, so outside all functions for example. This way the value where it is pointing to is not thrown away from the stack

I don't see a need to change this at the moment, but I will pin this issue to highlight it :-)
Thanks everyone!
