### ISSUE TITLE
Is it possible to force single column on wider screen? (question)

### ISSUE THREAD

**Issue by robvoi** [s00500/ESPUI#115]
This is actually a question, not a bug. Didn't find how to label it as question.

Is it possible to force all controls into a single column on wide screen?

The UI I created looks great on phones. On PC screen size the control order makes limited sense.

**Comment by s00500** [comment]
Not in the current implementation, you can only control the order of elements

**Comment by robvoi** [comment]
Thanks for the response.
And many thanks for providing this library. It made my project possible at all.

Maybe choosing the max amount of columns would be a good feature request?

**Comment by thomastech** [comment]
> Maybe choosing the max amount of columns would be a good feature request?

+1.

My dream solution would be a function that allows the max column value to change at any place so that "groups" of controls could be created. And separate the grouped controls with an optional frame and optional title/name (with control of title font  size and color).

- Thomas
