### ISSUE TITLE
OTA Update

### ISSUE THREAD

**Issue by robvoi** [s00500/ESPUI#116]
Hi. 
is it possible to have ESP32 UI combined with OTA Updates?
If so, does someone have n example on how to do it?

Thanks!

**Comment by sadatusa** [comment]
I am also interested in it very much. Tried couple of different OTAs without success.... Please help.

**Comment by robvoi** [comment]
> I am also interested in it very much. Tried couple of different OTAs without success.... Please help.

Have you tried a different OTA with own webserver on a different port?

**Comment by sadatusa** [comment]
Dear, I tried AsyncElegantOTA... no success... port 8080..
Thanks.

**Comment by robvoi** [comment]
Problem seems that all OTA implementations try to initiate <WebServer.h>.
Which is initiated already. It may be possible to adapt one of the libraries. But not sure what exactly has to be changed.
@s00500 I guess you have more knowledge that we have. Especially on the WebServer part. Any idea on an approach?

**Comment by chickey** [comment]
Would love this also, i went down a similar rabbit hold last night trying different solutions that are out there but ran into conflicts, ElegantOTA was the only one i could get to compile ok as i'm using asyncwifimanger but that won't work as ESPUI is starting the webserver itself and as mentioned it's already initiated so the other solutions don't compile out of the box.

**Comment by s00500** [comment]
Well to avoid the Webserver conflict (which would be inspected in more detail) I could recommend you to use HTTP GET style OTA, where the ESP would fetch the update binary from an external server

**Comment by robvoi** [comment]
This would indeed be good. But the device I am working on is in AP mode.

**Comment by enwi** [comment]
Wouldn't be that hard to support file upload @s00500 like in this [WebUpdate Example](https://github.com/esp8266/Arduino/blob/master/libraries/ESP8266WebServer/examples/WebUpdate/WebUpdate.ino)?

**Comment by enwi** [comment]
Just as a note: As a workaround I have been doing this so far:

```c++
const char* OTA_INDEX PROGMEM
    = R"=====(<!DOCTYPE html><html><head><meta charset=utf-8><title>OTA</title></head><body><div class="upload"><form method="POST" action="/ota" enctype="multipart/form-data"><input type="file" name="data" /><input type="submit" name="upload" value="Upload" title="Upload Files"></form></div></body></html>)=====";

void handleOTAUpload(AsyncWebServerRequest* request, String filename, size_t index, uint8_t* data, size_t len, bool final)
{
    if (!index)
    {
        Serial.printf("UploadStart: %s\n", filename.c_str());
         // calculate sketch space required for the update, for ESP32 use the max constant
        const uint32_t maxSketchSpace = (ESP.getFreeSketchSpace() - 0x1000) & 0xFFFFF000;
        if (!Update.begin(maxSketchSpace))
        {
            // start with max available size
            Update.printError(Serial);
        }
        Update.runAsync(true);
    }

    if (len)
    {
        Update.write(data, len);
    }

    // if the final flag is set then this is the last frame of data
    if (final)
    {
        if (Update.end(true))
        {
            // true to set the size to the current progress
            Serial.printf("Update Success: %ub written\nRebooting...\n", index + len);
            ESP.restart();
        }
        else
        {
            Update.printError(Serial);
        }
    }
}

void setupGUI
{
    ESPUI.begin("GUI");

    ESPUI.server->on("/ota", 
        HTTP_POST, 
        [](AsyncWebServerRequest* request) { request->send(200); }, 
        handleOTAUpload);

    ESPUI.server->on("/ota", 
        HTTP_GET, 
        [](AsyncWebServerRequest* request) {
            AsyncWebServerResponse* response = request->beginResponse_P(200, "text/html", OTA_INDEX);
            request->send(response);
        }
    );
}
```

**Comment by robvoi** [comment]
> Just as a note: As a workaround I have been doing this so far:
> ```

Thanks a lot for your post. I tried including your code. But it doesn't compile.
Which includes do you use?
Or can you maybe post a complete sketch with update+ESPUI.

**Comment by enwi** [comment]
@robvoi I've updated the example code (there where some braces missing after setupGUI)

**Comment by robvoi** [comment]
It works. That's fantastic.

You still have a typo in the code Updater.h -> Update.h 
Or are you using a different update library (could explain the below)

Had to remove `Update.runAsync(true);` as I got an error when compiling. `'class UpdateClass' has no member named 'runAsync'`

No idea why.

**Comment by enwi** [comment]
> You still have a typo in the code Updater.h -> Update.h
> Or are you using a different update library (could explain the below)
> 
> Had to remove `Update.runAsync(true);` as I got an error when compiling. `'class UpdateClass' has no member named 'runAsync'`

For ESP8266 you need to include `#include <Updater.h>` for ESP32 `#include <Update.h>` also for ESP32 `Update.runAsync(true);` is not needed and also 
```c++
const uint32_t maxSketchSpace = (ESP.getFreeSketchSpace() - 0x1000) & 0xFFFFF000;
        if (!Update.begin(maxSketchSpace))
```
should be replaced by
```c++
        if (!Update.begin(UPDATE_SIZE_UNKNOWN))
```

**Comment by sadatusa** [comment]
Great! thanks guys....

**Comment by toonnl** [comment]
Hi,
I had (I think) the same problem using ESPUI and ESP32 AsyncElegantOTA. 
Changed one line for OTA to:     AsyncWebServer server(8080);
ESPUI uses normal port 80
update OTA via:      <ip-address>:8080/update
Works fine, not sure if this solves the problem of @robvoi

**Comment by s00500** [comment]
I really like the solutions provided here, I do not think I will add OTA into ESPUI, its better if you combine it with external projects for that :-) Pinning this issue as further reference
