### ISSUE TITLE
IP address

### ISSUE THREAD

**Issue by Rumen33** [s00500/ESPUI#118]
Is there any way to configure an IP address, WiFi SSID, and password from an input field of the ESPUI ?

**Comment by Rumen33** [comment]
Solved. Sorry, I used text input and conversion from a string. You did a really good job. Thanks.

**Comment by s00500** [comment]
cool

**Comment by robvoi** [comment]
> Solved. Sorry, I used text input and conversion from a string. You did a really good job. Thanks.

Would be really great if you could post the code on how you change the IP. 
Do you store it to be persistent after reboot?
