### ISSUE TITLE
Add picture to page?

### ISSUE THREAD

**Issue by sadatusa** [s00500/ESPUI#119]
Dear thanks for nice lib... Is it possible to add picture to page??
Thanks

**Comment by robvoi** [comment]
A picture/logo would indeed be nice.

**Comment by nodoubtman** [comment]
> 
> 
> A picture/logo would indeed be nice.

Do you mean like the favicon ?

**Comment by nodoubtman** [comment]
Hello. Easy. You can edit index.htm in the data folder, then you change : 

to convert png to base64 image you can go on:  https://www.browserling.com/tools/image-to-base64

then drag and drop your png image converted to : 16x16

and take the converted the base64 string. and you can copy the whole string after the png;base64, until the >

after you can go to tools
and with python you type : python prepare_static_ui_sources.py --auto
in the directory, you have to install few modules, search on google :)

good luck!


      href="data:image/png;base64,                           iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAACxMAAAsTAQCanBgAAAAPdEVYdFNvdXJjZQBTTS1HOTUwV0wocgkAAAAWdEVYdFNvZnR3YXJlAEc5NTBXVkxTOENUSzFz7rpDAAAAB3RJTUUH5QUYFDM6/lhnvwAAACB0RVh0Q3JlYXRpb25UaW1lADIwMjE6MDU6MjQgMjA6NTE6NThOheFlAAAAIXRFWHRDcmVhdGlvbiBUaW1lADIwMjE6MDU6MjQgMjA6NTE6NTjGCoKjAAACgUlEQVQ4TzWTzU5TYRCG3zmnpVQK1KqAghplYzQoiUuXJhqXLNx7CRhMZMnKK3DhFbhyb2Ji3JB4Aca/GCNqQgOIxQK2tKdnfOYUm86Z7+d95/cbK9myu+9L1pUrkRyxkv7/3E1mnGnApidDm3IwiPqyVA/cVS7AUsqFAUQw5nHE3jzAQYqDMATRwtAgXFZYjCBjXI5COgF/DKmxHwc8yTqkyjocgTUw6ByHiRuHBhGABwEDYVQeaQSBqBTroeFwEnsLDSYJ7+4THNaxjFevsK+zP4dcxugM+/AehnHCOj82IiOaxNbc/FRxEEVMdUtnV+bVfQVsoaLRG6bdp9v6/fMNXpuQjsCGdNgfRgSTLPBKQSq6rQvrV7TfzrT77rOaz99r4/EPjT6qa+7uEqRZClodhk/kkR6lNshdFjPSxdNKfaC5F5u6c29a12/O6upCTY21AyVPSlTkWkEcdi0ixsCwxyE9pd87Ki2m+tIa0euXO9r40FTz6y+1WtxNJ3gOnKOjn8Nv4n6I6iu3LYqzpfbDni6tz6q8OK9BZ1btsSmln6bUW+kr00ewWYEP7TDwv+qJNYoqU02VfUHl6rzOL00qmxlRWsrUfNbSQfst8G+FVzcK6H/RhzxaW4V3hohKysk/1x6BNgBitCjuAbJLrgn37Yicf7d4nbn+BG3ZzeIdxCuMHDOAkRZVhmRF7zvcRaHjSfeQSIGnTEspYh9AG1ILEEMV/WVC/BgUeQbJwhvYNKlBmkCilVU07RgQZq5tDDUhtAFngKPPUahN1jFYMa2EzUQ6Trwo5n5M432vNcbV79Z11NnBSFg+wsgeoBhlouDxuGW07CR3kV5MJrPqXf0Dr60K1qcC0mMAAAAASUVORK5CYII="
    />

**Comment by s00500** [comment]
Very nice @nodoubtman
