### ISSUE TITLE
Sliders with a default value above 100 do not initialise at the correct position

### ISSUE THREAD

**Issue by eirinnm** [s00500/ESPUI#122]
**Describe the bug**
Sliders with a default value above 100 do not initialise at the correct position. They initialise at 100.

**To Reproduce**
Create a page with a single slider. I've given mine a range of 0-255 and a default value of 128.

    ESPUI.slider("Hue", &sliderCall, ControlColor::None, 128, 0, 255);

**Expected behavior**
When loading the page, the slider's position should be halfway along (128), instead of approximately 1/3rd of the way along, at position 100.

**Comment by zouden** [comment]
Furthermore: if you adjust the slider (say to position 200), then refresh the page, the slider jumps back to position 100. The label shows the correct value of 200.

**Comment by chamroeunbm** [comment]
Same issue. If I set the value to max, when I refresh it is not positioning at the right most.

**Comment by iangray001** [comment]
It looks like the actual "range" elements have the correct value attribute, it just needs updating into the rest of the DOM. I added this to the bottom of `controls.js::handleEvent` which seems to work.

`$(".range-slider__range").each(function(){ 
  $(this)[0].value = $(this).attr("value");
  $(this).next().html($(this).attr("value"));
});`
