### ISSUE TITLE
get text from text box?

### ISSUE THREAD

**Issue by sadatusa** [s00500/ESPUI#124]
Dear, I need to get text from Text Box. I know callback but I want to get it when I press a button.
Thanks
sadat

**Comment by Rumen33** [comment]
You can store your value into a string variable when the Text Box is changed:

ESPUI.addControl(ControlType::Text, "Your Text Box:", "Text", ControlColor::Alizarin, Control::noParent, &YourFunction);

String YourVariable;

void YourFunction( Control* sender, int type ) { 
 Your_Variable = sender->value;                             
  }

Then you can use this value when the button is pressed.
