### ISSUE TITLE
SPIFFS: mount failed

### ISSUE THREAD

**Issue by kbssa** [s00500/ESPUI#128]
I have a working code with ESPUI.begin("Test"), but if call ESPUI.beginSPIFFS("Test") the webserver doen't work and I got the error below when the code is initiallized:

`E (7830) SPIFFS: mount failed, -10025`

Is this a bug or I miss something ?

I am using a ESP-Wroom-32 Dev module.

**Comment by nodoubtman** [comment]
Hello. You can upload via the file system from tools menu in arduino ide :)

thanks.
Marc.

**Comment by s00500** [comment]
Please use the prepare filesystem sketch if you want to use SPIFFS, but this is not really recommended, using begin should do just fine
