### ISSUE TITLE
Port option parameter do not work, now it crashes as soon as receiving a client request after sending a page with only title and status...

### ISSUE THREAD

**Issue by nguzeldere** [s00500/ESPUI#138]
No it did not work, now it crashes as soon as receiving a client request after sending a page with only title and status as "Control Connected" for port 80,  I got same output for port number different than 80 as "Control Error/No Connection".  And as you can see title in your tabbed GUI example is "ESPUI Control" however it is seen as "Control" in the response as shown in the screen capture I provided in the linked issue.

_Originally posted by @nguzeldere in https://github.com/s00500/ESPUI/issues/137#issuecomment-955435278_

**Comment by iangray001** [comment]
I suspect this was caused by one of the transport issues that my recent fixes should have addressed. If you are still having issues after trying the new version, add a comment to issue #137
