### ISSUE TITLE
Browser Time feature

### ISSUE THREAD

**Issue by test3210-d** [s00500/ESPUI#140]
Hidden element  must return java Date.now()   value on request, or different way add this value for any event as additional variable.

**Comment by test3210-d** [comment]
i try add to all websock.send( ...... +" time="+Date.now()/1000) in dataControlsJS.h 
 
and modify  ESPUI.cpp
case WS_EVT_DATA:
    {
        String msg = "";
        msg.reserve(len + 1);

        for (size_t i = 0; i < len; i++)
        {
            msg += (char)data[i];
        }

        uint16_t id = msg.substring(msg.lastIndexOf(':') + 1).toInt();
        event_time =  strtoul(msg.substring(msg.lastIndexOf('=') + 1).c_str(),NULL,10) ;

this solution work for me. But I think what can be done better through a separate invisible element. I don’t know how to do it

**Comment by s00500** [comment]
Not entirely sure what you want to achive here... 

As I understand it you want to be able to access the client browser time for using as a timesource for your ESP ?

**Comment by test3210-d** [comment]
Yes, esp work in AP mode,  if i have time from client browser i can automatic set date/time in esp

**Comment by iangray001** [comment]
[I have implemented this feature in a branch on my fork](https://github.com/iangray001/ESPUI/tree/times). Check it out and we'll merge it into master at some point soon.

**Comment by iangray001** [comment]
Implemented in this [pull request](https://github.com/s00500/ESPUI/pull/152).
