### ISSUE TITLE
two same button or label

### ISSUE THREAD

**Issue by zhhq8008** [s00500/ESPUI#141]
Thanks for your job. I add an example as a lib to my project, when connected  ,it appears  Doble status and and tabs，I
do not know whats wrong

**Comment by zhhq8008** [comment]
![图片](https://user-images.githubusercontent.com/38678039/147306240-2a466958-8a83-4b55-a1e3-6e16296450b1.png)

**Comment by s00500** [comment]
Are you on esp32 or 8266 ? can you provide a bit more info about your setup ? Are you using one of the examples to test ?

**Comment by iangray001** [comment]
Closed due to lack of information. Reopen if you wish to provide more.
