### ISSUE TITLE
Issue with websocket : "Trame de continuation" stop websocket on webpage.

### ISSUE THREAD

**Issue by 051011** [s00500/ESPUI#15]
Hello,

I'm using your code for my application with an ESP32. I modified the code for me and I have a little problem with websocket. There are random disconnections (unexpected trame) and I don't know why. I use SPIFFS memory instead of .h for controls.js. 

Can you help me ? 

Thanks !

**Comment by s00500** [comment]
Hey,
Ok so let’s get the facts: Are you using the latest version of ESPUI 1.5.1 ? What versions of ESPAsyncWebserver and what version of the Arduino ESP32 core are you using?

What modifications did you make?

**Comment by 051011** [comment]
Thanks ! 
So i'm using the latest version for all ESPUI and ESPAsyncWebserver.
I added new labels with several displays in the same box. But the code has not changed much. I get sensor data in I2C on the ESPUI interface and that's it.

My mistake in more detail is this: When I go into the developer mode of the browser, I see this message
WebSocket connection to 'ws://192.168.4.1/ws' failed: Received unexpected continuation frame.

Have you an idea ?

**Comment by s00500** [comment]
ok, can you maybe post your code? Is there something blocking in your code ? Can you also check if there are errors on the Serial Monitor while this message comes up?
Does the esp reconnect afterwards when you press reload or is the connection dead? The last Idea would be using espui 1.5 without the SPIFFS stuff (just call ESPUI.begin() insead of ESPUI.beginSPIFFS())

**Comment by 051011** [comment]
No the connection is okay when i reload the web browser. For the UI part all seem to be okay... Maybe the web browser ?

**Comment by 051011** [comment]
[fichiers_github.zip](https://github.com/s00500/ESPUI/files/2094001/fichiers_github.zip)

**Comment by s00500** [comment]
ok, so what browser are you using? what exactly was the plan behind your modifications?

**Comment by 051011** [comment]
The plan was to print multiple data sensors in the UI and control integration time for example or other things. 
A note: When I display only one data, the continuation frame is not displayed. It will not be a problem of quantity of data in the Json ?

**Comment by s00500** [comment]
Why did you have to modify the library for this task? It should work just fine without modifications to fullfill your task 😃

You can use something like 

Char buffer[30];
sprintf(buffer, “Value 1:%d<br>Value 2:%d”, value1, value2);
ESPUI.print(0, String(buffer));

To print multiple values in one label
Or just use multiple labels

You can also use the slider element to input values

**Comment by 051011** [comment]
Okay !

I tried with a sprintf. It works just with "%d". If I put "%d plus one other thing" UI says ERROR. 
Have you an idea ?

Thanks !

**Comment by s00500** [comment]
Can you send me the sketch?

**Comment by 051011** [comment]
Ok it works now after restore library .. ! 
Do you know if it is possible to print values in column and not in line ? 
Like that : 
Value 1
Value 2
Value 3...

I tried \n with sprintf but it stays in line.... 

Thanks for all.

**Comment by s00500** [comment]
Use <br> for outputing a break in the Webinterface

https://lbsfilm.at
