### ISSUE TITLE
Visiblity option utilization

### ISSUE THREAD

**Issue by nguzeldere** [s00500/ESPUI#151]
İf visibile/invisible option is  available for controls it would be nice to include some description in the documentation and also provide application examples.

**Comment by nodoubtman** [comment]
Already exists check:

`
  uint16_t tabHome   = ESPUI.addControl( ControlType::Tab, "HOME &#127969;", F("HOME &#127969;") );

  timeLabel               = ESPUI.addControl(ControlType::Label, "TIME &#x231A;", F(""), COLOR_WETASPHALT, tabHome );


 ESPUI.getControl(timeLabel)->visible = 0;
  ESPUI.updateControl(timeLabel);

// update component
  ESPUI.jsonDom(0);`


also you can get it to visible to true with = 1;


etc..

I hope it helps :)
Marc.

**Comment by iangray001** [comment]
Added to this [pull request](https://github.com/s00500/ESPUI/pull/152/commits/576890e033406de7a37b4f788cf25a3abfd3790a). 

As per the documentation, once this is merged in, you'll just have to call `updateVisibility`.

**Comment by nodoubtman** [comment]
Thank YOu :)

Have a nice day.
Marc.

**Comment by nguzeldere** [comment]
> Added to this [pull request](https://github.com/s00500/ESPUI/pull/152/commits/576890e033406de7a37b4f788cf25a3abfd3790a).
> 
> As per the documentation, once this is merged in, you'll just have to call `updateVisibility`.

That would be great, thank you in advance..
