### ISSUE TITLE
Not working min/max value of an element when it is in a group.

### ISSUE THREAD

**Issue by Noctr** [s00500/ESPUI#158]
When I put the "Slider" or "Numberinput" element in the group, then the limiters do not work for them.
ESPUI.addControl(Max, "", ....     and ESPUI.addControl(Min, "", ....         do not work for such elements.
For "Slider" the range is always 0-100.
There are no restrictions for Numeric Input. 
(sorry for my bad english).

**Comment by iangray001** [comment]
Post your code please.

**Comment by Noctr** [comment]
[ESPUI_test.zip](https://github.com/s00500/ESPUI/files/8017193/ESPUI_test.

**Comment by iangray001** [comment]
Interesting. Yes it seems like there is a bug there that affects groups but not elements on their own.

It will be something quite simple, I'll fix it when I get a chance.

**Comment by thomastech** [comment]
@iangray001 I've seen this issue in other places too. It seems that programmable CSS that is applied to elements in a grouped control are ignored. 

That is to say, custom css works if the element is used on its own. But the css style is missing when the same element is moved into a grouped control.

- Thomas

**Comment by iangray001** [comment]
@Noctr I think I have fixed this now.

@thomastech I seem to be able to style grouped controls. Is there a specific scenario where it isn't being applied?

<img width="567" alt="Screenshot 2022-02-11 at 20 49 01" src="https://user-images.githubusercontent.com/7703247/153667997-a476807b-5375-41bb-918f-395ce521a9eb.png">

**Comment by thomastech** [comment]
>  I seem to be able to style grouped controls. Is there a specific scenario where it isn't being applied?

A recent scenario involved a Label Control grouped inside a Text Input Control. The Label's inline CSS was not working in this configuration. But worked fine outside the group. But it's not the only situation (I mentioned this issue a few weeks ago).

But I'm running your test PR from Jan-20 (very stable, solved many problems). So let me test again with your latest ESPUI code. All I need is the code you would like me to try out.

BTW, any chance you've added the feature that changes the color of the folder Tabs using something similar to  setElementStyle() or setPanelStyle()?

- Thomas
