### ISSUE TITLE
Behind a grouped control other controls get disabled

### ISSUE THREAD

**Issue by TinkerSteve** [s00500/ESPUI#162]
**Describe the bug**
after pulling the latest version of this lib from github, trying to take advantage of the fix for https://github.com/s00500/ESPUI/issues/158

I see some regression in my project. After adding a grouped slider control the next control is still working but the 2nd next is disabled ... no way to enable.

**To Reproduce**
use some code along these lines:

    setup_wifi();
    uint16_t slider1 = ESPUI.addControl(ControlType::Slider,"s1","",ControlColor::None,Control::noParent,&cb);
    uint16_t slider2 = ESPUI.addControl(ControlType::Slider,"s2","",ControlColor::None,slider1,&cb);
    uint16_t text_id = ESPUI.addControl(ControlType::Text,"Schedule","",ControlColor::None,Control::noParent,&cb);
    uint16_t slider3 = ESPUI.addControl(ControlType::Slider,"s3","",ControlColor::None,Control::noParent,&cb);
    // ESPUI.setEnabled(slider3, true); // won't change anything
    ESPUI.begin("Test");
    while (1)
    {
      delay(1000);
    }
**Expected behavior**
I would expect slider 3 enabled and functional.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/27211526/154052881-a8953f89-8e8e-48e9-be9c-7be8f7e4606e.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser firefox [97.0 (64-Bit)] , edge[ 98.0.1108.50]

**Additional context**
fails at commit e3e5c3495312c6a2a7e8f8e2dd8ea3bd5caa62cc
works at 7dcf6a10f4826dab487f16a6d647b4e7d9bbcea9

**Comment by iangray001** [comment]
Apologies, I must have missed something. I'll address ASAP.

**Comment by iangray001** [comment]
I think I see the issue. Seems that I didn't initialise the `enabled` value in the `Control` object. Silly me. Can you see if the [commit above](https://github.com/s00500/ESPUI/issues/162) addresses this? It's hard for me to recreate, but I assume this is the problem.

**Comment by TinkerSteve** [comment]
Hi, 

I can confirm this is fixed on the branch above.

Thanks for helping out that fast.
