### ISSUE TITLE
Is it possible to trigger an external API request?

### ISSUE THREAD

**Issue by daniel-frenkel** [s00500/ESPUI#166]
This GUI is incredible. I currently use AsyncTCP to trigger GET requests. For example, I'll send this from a different device to trigger a movement.

```
http://192.168.4.1/position?move=100
```

Is it possible to send HTTP requests to change the values of something like a slider or switch?

**Comment by thomastech** [comment]
Yes, very possible. I'm doing exactly that with ESPUI.

Port 80 is used by ESPUI, so you'll need to use port 8080 for WiFi Server GET. Other than that, nothing unusual needs to be coded.

BTW, this means your URL would look like this when sending to port 8080:
http://192.168.4.1:8080/position?move=100

- Thomas

**Comment by daniel-frenkel** [comment]
> Yes, very possible. I'm doing exactly that with ESPUI.
> 
> Port 80 is used by ESPUI, so you'll need to use port 8080 for WiFi Server GET. Other than that, nothing unusual needs to be coded.
> 
> BTW, this means your URL would look like this when sending to port 8080: http://192.168.4.1:8080/position?move=100
> 
> * Thomas

Thank you! 

That worked out perfectly

**Comment by AnakinSpain** [comment]
Can we change the port 80?

**Comment by iangray001** [comment]
Yes, it is an argument to the `begin` functions. [See here.](https://github.com/s00500/ESPUI/blob/5cf0ce6afa38511e80038131030b46a385de4f32/src/ESPUI.h#L108) 

`ESPUI.begin(HOSTNAME, USERNAME, PASSWORD, 12345);`
