### ISSUE TITLE
How to update text when pressing a button

### ISSUE THREAD

**Issue by daniel-frenkel** [s00500/ESPUI#167]
I am trying to get the user's WiFi credentials.

To do so,  I have two text inputs and one button

The user enters their wifi name into the first text box, then they click on the second text input and enter their password. 

Then they press the save button.

The problem is that after they input the password and press save, the password text box does not fire off the inputted text, and this leaves the box empty after they press save. 

Do you have any idea that can prevent this? Of course, the user can click somewhere outside the password text box or press enter to trigger the text to send, but that makes it more complicated to explain. 

It seems like if you press a button directly from a text box, the text does not send first

**Comment by iangray001** [comment]
The [completeExample](https://github.com/s00500/ESPUI/blob/master/examples/completeExample/completeExample.cpp) shows a way of doing this. Perhaps you could compare with what you are doing.

I draw your attention to the need to have [a callback for the text box, even if it doesn't do anything](https://github.com/s00500/ESPUI/blob/a958feb152089dc54d6576c442f3eeb26ab79fb5/examples/completeExample/completeExample.cpp#L515), if you want to listen to updates from it. Maybe it could be that.

**Comment by daniel-frenkel** [comment]
@iangray001 Thanks for that, I copied the way you did it in the example and it works perfectly. I didn't see this example within Arduino, but it's great to have it to reference. Thanks for your hard work on this
