### ISSUE TITLE
Update PlatformIO release to 2.1.1

### ISSUE THREAD

**Issue by hagre** [s00500/ESPUI#168]
**Describe the bug**
PlatformIO still has version 2.0.0 in the registry ( https://registry.platformio.org/libraries/s00500/ESPUI )
as found at https://docs.platformio.org/en/latest/librarymanager/creating.html a re-publish again is needet to be up to date.

thx

**Comment by iangray001** [comment]
@s00500 I have no idea how to push things into the PlatformIO registry... :)

Does it pull releases or a specific tag?

**Comment by s00500** [comment]
So basically the 2 info files in the repo needs to be set and then we need to make a release, I am currently in Amerika with very limited time and internet till in 2 weeks... but if we should try to make a release let me know

Usually the registry picks up the new tag and updates itself

**Comment by iangray001** [comment]
Hi Lucas, let's try to get this done. 

I believe `library.json` is fine, but presumably you need to push the update to PIO.

**Comment by hagre** [comment]
I found:

https://docs.platformio.org/en/latest/librarymanager/creating.html

[Publishing](https://docs.platformio.org/en/latest/librarymanager/creating.html#id3)[¶](https://docs.platformio.org/en/latest/librarymanager/creating.html#publishing)

You can publish a library to the [PlatformIO Registry](https://platformio.org/lib) using [pio pkg publish](https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_publish.html#cmd-pkg-publish) command. Every time when you modify a source code of a library you will need to increment the “version” field in [library.json](https://docs.platformio.org/en/latest/librarymanager/config.html#library-json) manifest and re-publish again.

If the published library has an issue and you would like to remove it from the PlatformIO Registry, please use [pio pkg unpublish](https://docs.platformio.org/en/latest/core/userguide/pkg/cmd_unpublish.html#cmd-pkg-unpublish) command.

**Comment by s00500** [comment]
Ok all so I think it was actually the keywords being too long as the main issue here... not sure though, it is published now anyway, I will keep the registry updated on every release from now
