### ISSUE TITLE
'Separator' was not declared in this scope

### ISSUE THREAD

**Issue by liwajaya** [s00500/ESPUI#171]
hello everyone, I'm trying to upload to ESP8266, it looks like this sample is different from the GUI sample,
error on this
'Separator' was not declared in this scope

please enlighten me
thank you

**Comment by iangray001** [comment]
Sorry I don't understand the question you're asking. However, given the error you're quoting, I suspect that you are probably using some older version of the library. [Try instead to use the version from this repository.
](https://github.com/s00500/ESPUI#how-to-install)
