### ISSUE TITLE
Integration with other HMI tool

### ISSUE THREAD

**Issue by garudaonekh** [s00500/ESPUI#174]
Hi,
I have used ESPUI for several projects. Recently, I come across FUXA( https://github.com/frangoteam/FUXA) which is HMI tool(don't know if it's correct to call like this) for PLC/SCADA.

I like its flow and animation so that user can understand more about the automation.

I want to integrate it with ESPUI, can anyone with better knowledge on these share me some insight or suggestion?

Regards;

**Comment by iangray001** [comment]
So something that you could probably try right now is creating a Label which just contains the HTML of an [iframe](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe) that points to the web interface of this project. That should all just work out of the box.

I've not tried creating an iframe within ESPUI, but...it should just work I think.
