### ISSUE TITLE
Using ESPUI with custom AsyncWebserver Setup

### ISSUE THREAD

**Issue by tx73github** [s00500/ESPUI#18]
I'd like to use the ESPUI along with the AsyncWebserver serving html and using the great SpiffsEditor which makes changes so much faster.
Latest in server.begin() vs ESPUI.beginSPIFFS() in the sketch shows the problem. Any suggestion ? In the end espui lib configures the webserver and a sketch does the same. It maybe helps #16 and #17 as well. Thanks, Thorsten

**Comment by s00500** [comment]
Ok, could you please post your code, your error, your setup or any other hint that could help me understand the problem better?

**Comment by tx73github** [comment]
Sure,
I try to run the ESPAsyncWebserver incl. SPIFFsEditor.
On index.htm I would like the ESPUI widgets to control some functionalities.
But on configuration the ESPAsyncWebServer collides with configurations of the ESP lib from ESPUI, which is clear, but both could co-exist I hope.

sketch:
#include <ESPAsyncWebServer.h>
#include <SPIFFSEditor.h>
#include <ESPUI.h>

void slider(Control sender, int type) {
  Serial.println(sender.value);
}
[...]
AsyncWebServer server(80);
AsyncWebSocket ws("/ws");
AsyncEventSource events("/events");

void setup();
server.addHandler(new SPIFFSEditor(http_username,http_password));
server.serveStatic("/", SPIFFS, "/").setDefaultFile("index.htm");
server.serveStatic("/web", SPIFFS, "/www/start.htm");

ESPUI.label("Status:", COLOR_TURQUOISE, "Stop");

ESPUI.begin("ESPUI Control");
server.begin();
//latest here the issue becomes obvious. Both are trying to start  "the" webserver.

void loop() {};

**Comment by s00500** [comment]
Well since ESPUI Uses ESPAsync Webserver there is not really a way to use the two together other than hacking into the library and providing a getter for the Server object.... but tis is not really what this lib is meant for...

**Comment by s00500** [comment]
Closing because inactive
