### ISSUE TITLE
vertical groups for number, text fields or positioning of controls

### ISSUE THREAD

**Issue by knopserl** [s00500/ESPUI#188]
Although I like this simple and easy to use WEb-UI Lib, I miss some essential features or at least I don't know how to solve it with the current version which is creating some forms with ordered, positioned fields without having panels for each control.

An example: In a settings tab, I wanted to create a vertical ordererd field list with some number fields (IP-Address, Network-Mask, Gateway, DNS etc.) I wanted that in a group called network settings and I wanted the input fields vertically ordered.
I guess that is not yet supported for number and text and as a result, the fields are ordered horizontally.
It would be very nice if all fields could be placed with a kind of postion or at least in columns nad rows (like a grid or table) and the rows and colums should be sizable so that some positioning is possible. Currently this is extremly limited, 
Also only normal or wide (boolean) is supported and not a width.
BTW: A IP-Address control would be also very nice as this is needed in almost every application.

see how much space that is using instead of one group "Network Settings" und 4 fields + save. Each text or number field needs of course a label on the left side:

![grafik](https://user-images.githubusercontent.com/36055354/179368874-4bdc400d-15a6-479c-97a7-c8fb5e7ff065.png)

**Comment by iangray001** [comment]
So the library was designed (I presume) to be very lightweight, and not include an entire layout engine. That said I'm always interested if people can think of small, backwards-compatible changes, to improve flexibility.

However, I think the thing that you want actually is supported.

The [Grouped Controls](https://github.com/s00500/ESPUI#grouped-controls) feature lets you put multiple controls into a single panel, and then style them however you want:
https://github.com/s00500/ESPUI/raw/master/docs/ui_groupedbuttons3.png

**Comment by knopserl** [comment]
unfortunatly it is not yet supported (at least not that I'm aware) and I think the thing I wanted to do is a very very basic requirements.
Place in one panel just a list of fields vertically with a prompt on the left side (in front of the input field)
The current "vertically support" is only for sliders and switches (as shown in the examples) and not for text, numbers etc.

Something like:
![grafik](https://user-images.githubusercontent.com/36055354/179370839-73d85b5e-c3a9-457b-b6e3-24ffdbb8c6e3.png)

or this is an exact sample: just prompt + input fields, and next prompt  + field in next line (vertically), no complicated layout management just rows and cols like a grid/table or a way to specify which control should be placed in next rows (opens a new row)
![grafik](https://user-images.githubusercontent.com/36055354/179371199-5826a3f6-1995-4844-9f63-3cef26629ad9.png)

**Comment by iangray001** [comment]
Well as I said, this project is not a UI framework. If you want a layout engine, use HTML and CSS. 

```
	String labelStyle = "background-color: unset; width: 20%;";
	String inputStyle = "width: 70%;";

	auto exgroup = ESPUI.addControl(Label, "Example Group", "Val 1", None, maintab);
	ESPUI.setElementStyle(exgroup, labelStyle);
	ESPUI.setElementStyle(ESPUI.addControl(Text, "", "", Peterriver, exgroup, generalCallback), inputStyle);

	ESPUI.setElementStyle(ESPUI.addControl(Label, "", "Val 2", None, exgroup), labelStyle);
	ESPUI.setElementStyle(ESPUI.addControl(Text, "", "", Peterriver, exgroup, generalCallback), inputStyle);

	ESPUI.setElementStyle(ESPUI.addControl(Label, "", "Val 3", None, exgroup), labelStyle);
	ESPUI.setElementStyle(ESPUI.addControl(Text, "", "", Peterriver, exgroup, generalCallback), inputStyle);
```

<img width="629" alt="Screenshot 2022-07-17 at 11 17 35" src="https://user-images.githubusercontent.com/7703247/179393819-a178a11f-b0e6-4292-b285-d1c6e80b1d57.png">

You can add more CSS to tweak the arrangement, but this is the minimal.

Note that in preparing this for you I found a small bug in applying styles to text elements, [for which I just created a PR](https://github.com/s00500/ESPUI/pull/190). So use that code if you want to play around and it hasn't been merged yet.

**Comment by knopserl** [comment]
@iangray001 thanks, that looks already like I was looking for and will use your styles. 
Other than that, I'm fine with the features provided by the library, as it is simple to use and helpful and saves time.

**Comment by Atorcha** [comment]
> @iangray001 thanks, that looks already like I was looking for and will use your styles as well as your PR code. Other than that, I'm fine with the features provided by the library, as it is simple to use and helpful and saves time.
> 
> Here is the desired result ![grafik](https://user-images.githubusercontent.com/36055354/179426277-9b9bce75-5ca7-474c-93c5-f8db380c14fa.png)

I would like to know how make that!!! 

It is a good way to show data of my project....

**Comment by iangray001** [comment]
I added example code in this very thread to do this. 

https://github.com/s00500/ESPUI/issues/188#issuecomment-1186471559

You should be able to see how to adapt that to your needs.

**Comment by Atorcha** [comment]
Hi, I am trying to do but I cann´t.


```
 //MODO FUNCIONAMIENTO LUZ
  auto select1 = ESPUI.addControl(ControlType::Label, "Configuracion luz", "MODO", ControlColor::Peterriver, param_tab);
    ESPUI.setElementStyle(select1, labelStyle);
    auto select1b = ESPUI.addControl(ControlType::Select, "", "", ControlColor::Peterriver, select1, selectCall);
      ESPUI.setElementStyle(select1b, labelStyle);
      ESPUI.setElementStyle(ESPUI.addControl(ControlType::Option, "MODO AUTO", "MODO AUTO", ControlColor::Peterriver, select1b), inputStyle);
      ESPUI.setElementStyle(ESPUI.addControl(ControlType::Option, "MODO ON", "MODO ON", ControlColor::Peterriver, select1b), inputStyle);
      ESPUI.setElementStyle(ESPUI.addControl(ControlType::Option, "MODO OFF", "MODO OFF", ControlColor::Peterriver, select1b), inputStyle);
    ESPUI.setElementStyle(ESPUI.addControl(Label, "", "Hora ON", Peterriver, select1), labelStyle);   // INTRODUCCION HORA ENCENDIDA/APAGADA
    ESPUI.setElementStyle(text_time1 = ESPUI.addControl(Text, "", luz_on_temp, Peterriver, select1, luz_on_Callback), inputStyle); // INPUT ON DEL PRIMER TIMER
    ESPUI.setInputType(text_time1, "time");
    ESPUI.setElementStyle(ESPUI.addControl(Label, "", "Hora OFF", Peterriver, select1), labelStyle); 
    ESPUI.setElementStyle(text_time2 = ESPUI.addControl(Text,"", luz_off_temp, Peterriver, select1, luz_off_Callback), inputStyle); // INPUT OFF DEL PRIMER TIMER
    ESPUI.setInputType(text_time2, "time");
```

<img width="563" alt="Captura de pantalla 2024-01-21 a las 14 04 52" src="https://github.com/s00500/ESPUI/assets/4932853/792d6fb4-7cab-4767-97bd-3d37ace7af48">

**Comment by iangray001** [comment]
Do you understand what what these two lines in my example are?

```
String labelStyle = "background-color: unset; width: 20%;";
String inputStyle = "width: 70%;";
```

So ESPUI is not a layout engine, it connects a web page with basic HTML controls to code running on an ESP. That front end page is necessarily quite basic. I added a feature to allow [inline CSS styles](https://www.w3schools.com/css/css_howto.asp) to the HTML controls to allow for a bit more flexibility, but that is all. 

When you create a control normally in ESPUI, it is the full width of the blue box. Therefore if you create two controls the second one wraps around onto the next line. In this thread, I showed how you can style inputs (the text box) to be only 70% of the width of the box, so therefore a label of 20% width will appear on the same line before any subsequent ones wrap to the next line.

There is nothing clever going on here, just filling up each line until it wraps onto the next.

You have added three things that fit on the top line (`MODO`, the drop down, and `Hora ON`) so your web browser has laid them out on one line. The next two things then fit on the next line, then the last thing on the last line.

So there are a few fixes.

1. Add the `MODO` and dropdown *last*. Everything will then line up properly (but they will be at the bottom)
2. Customise the width of the `MODO` and dropdown to be wide enough on their own. So instead of setting the dropdown to use the `inputStyle` you could create another style like `"background-color: unset; width: 60%;";` and play with that 60 number until it is wide enough to push the `Hora OFF` label onto the next line.
3. Add an empty label without a style after the dropdown which will act like a carriage return.
