### ISSUE TITLE
  want to add a function to the module

### ISSUE THREAD

**Issue by lyalove** [s00500/ESPUI#19]
Hello, your espui is a very good module.
I hope this module adds a function, a button is associated with a pin port, and the state of the pin port is fed back.
Feedback pin port has high or low level, or analog value, feedback to the web page, color change, or numerical display.
  thks

**Comment by s00500** [comment]
Hi again,
What you want can easily be done already.

Create a label using ESPUI.label()
Then check for a value change on your pin / analog input or whatever. (You only want to send a message to the UI when there is actual new data)
Simple css can be used to give your elements color and can then be changed by sending a different value.

Your code could look something like this:
`
bool oldstate = false;
if(digitalRead(pin)!=oldstate) {
char buf[5];
sprintf(buff, "<p style='color:red'>%d</p>",digitalRead(pin));
ESP.print("PinState", buff);
oldstate = digitalRead(pin);
}
`
