### ISSUE TITLE
How to remove an option into a select input..

### ISSUE THREAD

**Issue by nodoubtman** [s00500/ESPUI#191]
Hello.
How to remove an option into an select input ?

Thanks.
Marc.

**Comment by iangray001** [comment]
Can't you just remove the Select control with `ESPIU.removeControl()` and then refresh the UI with `jsonReload()`?

**Comment by iangray001** [comment]
I'm confused. You create a select and its options with:

```
auto select1 = ESPUI.addControl( ControlType::Select, "Select Title", "Initial Value", ControlColor::Alizarin, tab1, &selectExample );
auto opt1 = ESPUI.addControl( ControlType::Option, "Option1", "Opt1", ControlColor::Alizarin, select1);
auto op2 = ESPUI.addControl( ControlType::Option, "Option2", "Opt2", ControlColor::Alizarin, select1);
```

so you can remove then with 

```
ESPIU.removeControl(opt1);
```

**Comment by nodoubtman** [comment]
@iangray001 thank you its works :)

Good day.
Marc.

**Comment by nodoubtman** [comment]
@iangray001 thank you its works :)

Good day.
Marc.

**Comment by iangray001** [comment]
Awesome, good stuff.
