### ISSUE TITLE
Not really a bug...

### ISSUE THREAD

**Issue by nodoubtman** [s00500/ESPUI#194]
Hello, I would like to know where is ESPUI-charts.zip

thank you.
Marc.

**Comment by iangray001** [comment]
I'm not sure what you are asking here. What `.zip` are you referring to?

**Comment by orithena** [comment]
I believe they're referring to the minified and gzipped graph.js. It's not on the filesystem, it's written into the byte array JS_GRAPH_GZIP to dataGraphJS.h and used when serving files from PROGMEM.

Use tools/prepare_static_ui_sources.py to regenerate those header files from non-minified sources (see also README.md, section "Notes for development")

**Comment by nodoubtman** [comment]
> I'm not sure what you are asking here. What `.zip` are you referring to?

A while ago you have posted a new ESPUI that could draw chars, gauge, line chart, bar graph.
I don't know where to find it?

Have a good day.
Marc.

**Comment by orithena** [comment]
Marc, what exactly are you trying to accomplish? Now it sounds like you ask "how to upgrade the ESPUI library to the newest version?"

There are multiple options, depending on how you originally installed it:
- Manual (ZIP): Download the 2.1.1 release zip from the project's github front page and unpack it over your existing library folder.
- Manual (GIT): Go into the existing library folder and do a `git pull`
- Arduino IDE: Use Sketch -> Include Libraries -> Manage Libraries, then find ESPUI and update to 2.1.1.
- PlatformIO: Run `pio pkg update`

**Comment by nodoubtman** [comment]
Hey, finally i found it in my emails:
here is it:

https://github.com/iangray001/ESPUI/tree/charts#charts

thanks.
Marc.

**Comment by nodoubtman** [comment]
Solved
