### ISSUE TITLE
Problem with prepareFilesystem

### ISSUE THREAD

**Issue by habkorn** [s00500/ESPUI#2]
Hi,

a JSON file is missing in the Library  (ArduinoJson.h):

Arduino: 1.8.5 (Windows 7), Board: ""WeMos" WiFi&Bluetooth Battery, 80MHz, 921600"
In file included from C:\Users\ent42\Documents\Arduino\libraries\ESPUI\examples\prepareFilesystem\prepareFilesystem.ino:1:0:

C:\Users\ent42\Documents\Arduino\libraries\ESPUI\src/ESPUI.h:7:25: fatal error: ArduinoJson.h: No such file or directory

compilation terminated.

exit status 1
Fehler beim Kompilieren für das Board "WeMos" WiFi&Bluetooth Battery.

**Comment by s00500** [comment]
Hey, what version of the ArduinoJson library do you have installed? Is it the latest?

**Comment by s00500** [comment]
Please make sure to install all dependencys like the ArduinoJson library (via the library manager)

**Comment by s00500** [comment]
When this fixed your problem please let me know

**Comment by s00500** [comment]
Closing because of no response
