### ISSUE TITLE
Storing Config in NVM, best practices example

### ISSUE THREAD

**Issue by elockman** [s00500/ESPUI#213]
**Is your feature request related to a problem? Please describe.**
The examples do not store the config in NVM. If the device is rebooted, the config is lost. 

**Describe the solution you'd like**
After looking at the code, it appears the HTML, JS, and CSS are stored in LittleFS, however the config is all stored in RAM. The purpose of ESPUI is presumed to edit configurations, which should be stored in NVM.  I understand that these configs can be stored in Flash (LittleFS) or in a separate EEPROM, but I would like to see example code for storing configs with best practices.

**Describe alternatives you've considered**
One problem I am running into is sender->id changing if an element is added into the configuration. One thought was to add a struct that provides a lookup between the app id and the sender->id. I'm new to this library, and would like to know if anyone has a solution they would like to share. I think there would be more users if the existing UI examples included code to store configs in NVM.

**Additional context**
I would rather not re-invent the wheel, but if nobody has recommendations I'll come up with something.

**Comment by thomastech** [comment]
> Do any of you have example code you would be willing to share that pulls and stores configuration data from/to LittleFS?

I save / restore several config items via LittleFS (and SD Card). See the _src/backup.cpp_ file in my FM transmitter project: https://github.com/thomastech/PixelRadio

- Thomas

**Comment by elockman** [comment]
@thomastech that is a huge help. Thank You!
