### ISSUE TITLE
How to use a “Options” drop-down list outside of a tab-menu

### ISSUE THREAD

**Issue by AWSW-de** [s00500/ESPUI#214]
First of all: A big thanks for this well done interface! 

I am currently working on a new [3D printable WordClock](https://www.printables.com/de/model/331012-wordclock-16x16-led-matrix) project and started to use your interface, because it saves me tons of time. Before I wrote an html configuration page manually and after some time while adding more and more functions it was not good to manage…

This is more a question than a bug, but with the given examples I could not figure out how to use a “Options” drop-down list outside of a tab-menu. I want to add a drop down list to select the language of the WordClock layout and interface as well. The values are stored in a int variable as “0” for German and f.e. “1” for English language….

Can you please add an example how to add such an options menu to achieve this ?

Thanks in advance! =)

**Comment by AWSW-de** [comment]
Thanks a lot! 
I will have a look at this. Thanks for the hint as well.
Kind regards

**Comment by AWSW-de** [comment]
Hello,
sorry i need to come back to this topic. Had a deep look into the linked files and they all use the tab option too...

Can you give me short example of an option list without the tab usage?

Thanks in advance :)

Kind regards

**Comment by cormalenv** [comment]
For those that come across this question and to close it off...

In ESPUIO.cpp,  the basic control functions such as ESPUI.button() or ESPUI.slider()), ESPUI.text() are built on the more complex "addControl" with "Control::noParent" for the tab variable. 

You can therefore use "Control::noParent" for the tab variable in the constructor of the Select control type eg

`ESPUI.addControl( ControlType::Select, "Title", "Default Option", ControlColor::Dark,Control::noParent,selectCallback);`

**Comment by AWSW-de** [comment]
Thanks for the hint. I will try that soon. =)

**Comment by AWSW-de** [comment]
> For those that come across this question and to close it off...
> 
> In ESPUIO.cpp, the basic control functions such as ESPUI.button() or ESPUI.slider()), ESPUI.text() are built on the more complex "addControl" with "Control::noParent" for the "parentalControl" (eg tab) variable.
> 
> You can therefore use "Control::noParent" for the "tab" variable in the constructor of the Select control type eg
> 
> `ESPUI.addControl( ControlType::Select, "Title", "Default Option", ControlColor::Dark,Control::noParent,selectCallback);`

Works fine, thanks a lot :)

**Comment by AWSW-de** [comment]
Closed
