### ISSUE TITLE
Calling Callbacks via raw HTML

### ISSUE THREAD

**Issue by fiskn** [s00500/ESPUI#216]
It would be handy if you could call a callback via the use of a direct html link <a>

In my project I'm using ESPUI.print into a Label, to display a dynamically generated HTML table of nodes in a mesh network. I wish to be able trigger certain actions to each of the line items, like sending a restart command.

I was hoping there might be someway in the current code I could add a <a href=XXXX> into one of the table cells and when clicked it would call a URL which would be passed through to a callback. Or even if you could inline some JS to call a callback via websockets.

Are you aware if there is anything in the current codebase I could manipulate to achieve this?

**Comment by s00500** [comment]
you should be able to get the actual Webserver out and register further handlers, very similar to how it is done here
https://github.com/s00500/ESPUI/issues/116
