### ISSUE TITLE
Support line breaks

### ISSUE THREAD

**Issue by CltAvi8tor** [s00500/ESPUI#22]
How difficult would it be to add a "control" item that acts as a standard line break? I'm trying to build an app that has various controls on a page that I want stacked vertically for some controls, while others would use the standard flow layout.

Thanks!

**Comment by s00500** [comment]
Hm Cool Idea... I'll add it to the list... basically it would be not to hard to do, add a new control type (like "break" or so) and then make the necessary changes in the controls.js part, reminimize everything and test....

I am always open to pull requests ;-)

**Comment by CltAvi8tor** [comment]
Weeeelll i might be coerced to do that, I'll need to get familiar with the way you're wrapping the requests into the controls - you have any "notes" you can share? I don't mind contributing at all; matter of fact, I think we could add a few things like layouts (tables? columns? you get the idea) to make the flows controllable based on the device. E.g. a single column of controls would be better on a small screen, whereas the same set might best be rasterized as several columns/rows on a bigger screen. Kind of like the way Visual Studio's "Flow Layout Control" works but better...

Thoughts?

**Comment by s00500** [comment]
Hm no not really, but I can actively review your stuff, make your changes on a fork and I'll check and give input :-) But I can recommend you to use a codeformater, I have been using the atom-beautify package

**Comment by s00500** [comment]
This seems to be the right place to discuss layout changes...
@CltAvi8tor is your offer for contribution still standing?
