### ISSUE TITLE
slider max 100

### ISSUE THREAD

**Issue by Alyavin** [s00500/ESPUI#220]
Hi, why is the slider only maxing out at 100? How can I make 360?

**Comment by iangray001** [comment]
The default bounds of a slider are 0-100. If you want to change that you can add `min` and `max` controls. See the [completeExample](https://github.com/s00500/ESPUI/blob/5cf0ce6afa38511e80038131030b46a385de4f32/examples/completeExample/completeExample.cpp#L90).

**Comment by Alyavin** [comment]
thanks
