### ISSUE TITLE
trying to understand library

### ISSUE THREAD

**Issue by AnakinSpain** [s00500/ESPUI#223]
Hello, I am trying to understand the library but I cann´t. I have two problems that I can solve.

1)  Try to make a group with a TITLE, and inside introduce two values Humidity and Temperature that are read from my DHT22 sensor

    auto tab1 = ESPUI.addControl(Tab, "", "Status");
    
    // grupo de datos habitacion
    auto grouplabel_1 = 
    ESPUI.addControl(Label, "Habitacion", "",  Turquoise, tab1, generalCallback);
    tempHBLabelId = ESPUI.addControl(Label, "", "", ControlColor::Turquoise, grouplabel_1); // temp habitacion
    humedadHBLabelId = ESPUI.addControl(Label, "", "", ControlColor::Turquoise, grouplabel_1); //humedad habitacion
    ESPUI.setElementStyle(grouplabel_1, "font-size: x-large; font-family: serif;");

![hab1](https://user-images.githubusercontent.com/4932853/219368506-f86c6635-3dcd-4514-8787-99ecd0df2d72.png)

2) Try to make a group to enter de TIME that a timer will be ON and another time to enter the time that will be OFF

    auto grouplabel_3 = 
    ESPUI.addControl(Label, "Luz", "",  Turquoise, tab2);
    text_time1 = 
    ESPUI.text("Time 1", time1_Callback, ControlColor::Dark, "01:00"); // INPUT ON DEL PRIMER TIMER
    ESPUI.setInputType(text_time1, "time");
    
    text_time2 = 
    ESPUI.text("Time 2", time2_Callback, ControlColor::Dark, "02:00"); // INPUT OFF DEL PRIMER TIMER
    ESPUI.setInputType(text_time2, "time");
    
    ESPUI.setElementStyle(grouplabel_3, "font-size: x-large; font-family: serif;");
![hab2](https://user-images.githubusercontent.com/4932853/219370648-21a169b9-07d2-4b87-8223-3140a959b9aa.png)

thanks

**Comment by iangray001** [comment]
You've not actually explained what your problems are.

**Comment by AnakinSpain** [comment]
The first problem is show better the information without gray lines between the tittle and the numbers

The Second problem is show the two cards in only one card

**Comment by iangray001** [comment]
That question is too vague for me to answer.

I presume that you want the user to input time as a string. Entering "23:21" is a lot easier than 1462836372. You will need to work out a suitable format that you want to use, parse and validate it when it is submitted, and then convert it into something that is compatible with whatever time source use are using.

**Comment by AnakinSpain** [comment]
sorry I try to explain me better.
 I obtein the real time in this way:  I have the hour in ine int, and minute in other int, so I have this operation: realtime =(hour*60)+minute
Then I will like to compare with the time input to trigger a relay.

**Comment by iangray001** [comment]
`sender->value` is a string with two numbers separated by a colon `:`, `toInt()` is only expecting a string representation of a **single** number. If we look at [the documentation for toInt()](https://www.arduino.cc/reference/en/language/variables/data-types/string/functions/toint/) we read:

> If the String contains non-integer numbers, the function will stop performing the conversion.

This is why it converts "23:40" into 23. It gets to the `:` and stops. 

What we need to do is first search for where in the string the `:` is, and then convert the first half into hours and the second half into minutes. There are lots of ways of doing it but you could do something like this.

Bear in mind I am currently travelling so I haven't been able to compile or test any of this. It should give you the idea though.

```
//Convert the hours. Rely on the fact that it will stop converting when it hits the :
int hours = sender->value.toInt();
//Look for the : 
char *mins_str = strstr(sender->value.c_str(), ":");
//strstr returns a pointer to where the : was found. Increment past it.
mins_str += 1;
//And finally convert the rest of the string.
int mins = String(mins_str).toInt();
```
