### ISSUE TITLE
Example of how to set min and max values for slider

### ISSUE THREAD

**Issue by jackthese** [s00500/ESPUI#225]
None of the provided examples show how to set min and max values for a slider control. They all appear to default to min=0 and max=100.  I've looked at the library code and its complexity is beyond my comprehension. My starting point from one of the examples is

ESPUI.addControl(ControlType::Slider, "MotorRPM", "30", ControlColor::Alizarin, Control::noParent, &slider);

This line created a slider from 0 to 100 with the value set to 30.  What do I need to add or modify to set new min and max values?

**Comment by iangray001** [comment]
The [completeExample](https://github.com/s00500/ESPUI/blob/5cf0ce6afa38511e80038131030b46a385de4f32/examples/completeExample/completeExample.cpp#L89)  shows it.

**Comment by jackthese** [comment]
Indeed, and somehow I had missed it. Works perfectly to set a stepper motor RPM for some testing I'm doing. Thanks very much for your quick reply...

  uint16_t mainSlider = ESPUI.addControl(ControlType::Slider, "MotorRPM", "100", ControlColor::Alizarin, Control::noParent, &slider);
  ESPUI.addControl(Max, "RPM", "320", None, mainSlider);
