### ISSUE TITLE
json issue while compiling

### ISSUE THREAD

**Issue by jeaoks** [s00500/ESPUI#24]
Hi,

i do think that i have some issue with related to json's.

I already found all the missing libraries where your code referred to, but this is now my next problem to get it compiled. 

THanks your help in advance!

BR
Jussi

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp: In member function 'void ESPUIClass::print(int, String)':

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:423:5: error: 'StaticJsonBuffer' was not declared in this scope

     StaticJsonBuffer<200> jsonBuffer;

     ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:423:5: note: suggested alternative:

In file included from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/StaticJsonDocument.hpp:8:0,

                 from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:10,

                 from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.h:7,

                 from C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:1:

C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/StaticJsonBuffer.hpp:110:7: note:   'ArduinoJson::Internals::StaticJsonBuffer'

 class StaticJsonBuffer : public Internals::StaticJsonBufferBase {

       ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:423:27: error: 'jsonBuffer' was not declared in this scope

     StaticJsonBuffer<200> jsonBuffer;

                           ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:428:10: error: 'class ArduinoJson::JsonObject' has no member named 'printTo'

     root.printTo(json);

          ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp: In member function 'void ESPUIClass::updateSlider(int, int, int)':

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:450:5: error: 'StaticJsonBuffer' was not declared in this scope

     StaticJsonBuffer<200> jsonBuffer;

     ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:450:5: note: suggested alternative:

In file included from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/StaticJsonDocument.hpp:8:0,

                 from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:10,

                 from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.h:7,

                 from C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:1:

C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/StaticJsonBuffer.hpp:110:7: note:   'ArduinoJson::Internals::StaticJsonBuffer'

 class StaticJsonBuffer : public Internals::StaticJsonBufferBase {

       ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:450:27: error: 'jsonBuffer' was not declared in this scope

     StaticJsonBuffer<200> jsonBuffer;

                           ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:455:10: error: 'class ArduinoJson::JsonObject' has no member named 'printTo'

     root.printTo(json);

          ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp: In member function 'void ESPUIClass::updateSwitcher(int, bool, int)':

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:467:5: error: 'StaticJsonBuffer' was not declared in this scope

     StaticJsonBuffer<200> jsonBuffer;

     ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:467:5: note: suggested alternative:

In file included from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/StaticJsonDocument.hpp:8:0,

                 from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:10,

                 from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.h:7,

                 from C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:1:

C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/StaticJsonBuffer.hpp:110:7: note:   'ArduinoJson::Internals::StaticJsonBuffer'

 class StaticJsonBuffer : public Internals::StaticJsonBufferBase {

       ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:467:27: error: 'jsonBuffer' was not declared in this scope

     StaticJsonBuffer<200> jsonBuffer;

                           ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:472:10: error: 'class ArduinoJson::JsonObject' has no member named 'printTo'

     root.printTo(json);

          ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp: In member function 'void ESPUIClass::updateNumber(int, int, int)':

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:492:5: error: 'StaticJsonBuffer' was not declared in this scope

     StaticJsonBuffer<200> jsonBuffer;

     ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:492:5: note: suggested alternative:

In file included from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/StaticJsonDocument.hpp:8:0,

                 from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:10,

                 from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.h:7,

                 from C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:1:

C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/StaticJsonBuffer.hpp:110:7: note:   'ArduinoJson::Internals::StaticJsonBuffer'

 class StaticJsonBuffer : public Internals::StaticJsonBufferBase {

       ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:492:27: error: 'jsonBuffer' was not declared in this scope

     StaticJsonBuffer<200> jsonBuffer;

                           ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:497:10: error: 'class ArduinoJson::JsonObject' has no member named 'printTo'

     root.printTo(json);

          ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp: In member function 'void ESPUIClass::jsonDom(AsyncWebSocketClient*)':

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:547:5: error: 'StaticJsonBuffer' was not declared in this scope

     StaticJsonBuffer<200> jsonBuffer;

     ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:547:5: note: suggested alternative:

In file included from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/StaticJsonDocument.hpp:8:0,

                 from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.hpp:10,

                 from C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson.h:9,

                 from C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.h:7,

                 from C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:1:

C:\Users\NNN\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/Memory/StaticJsonBuffer.hpp:110:7: note:   'ArduinoJson::Internals::StaticJsonBuffer'

 class StaticJsonBuffer : public Internals::StaticJsonBufferBase {

       ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:547:27: error: 'jsonBuffer' was not declared in this scope

     StaticJsonBuffer<200> jsonBuffer;

                           ^

C:\Users\NNN\Documents\Arduino\libraries\ESPUI\src\ESPUI.cpp:559:10: error: 'class ArduinoJson::JsonObject' has no member named 'printTo'

     root.printTo(json);

          ^

exit status 1
Error compiling for board ESP32 Dev Module.

**Comment by s00500** [comment]
hm ok, so what version of ArduinoJson do you have installed?

**Comment by mrzottel** [comment]
I had the same issue using ArduinoJson 6.4.0-beta. Moving back to 5.13.1 solved it.

**Comment by s00500** [comment]
@mrzottel Thanks for your comment, closing this now
