### ISSUE TITLE
Newest "ESPUI-master" does not compile "ESPUI.cpp:58:5: error: 'result' was not declared in this scope"

### ISSUE THREAD

**Issue by AWSW-de** [s00500/ESPUI#243]
Hello,
some of my users reported that they receive the following error with the newest download of the "ESPUI-master.zip".
Within Arduino IDE i did not get an update notification that there is a newer ESPUI version, but after i removed my local copy of your library and downloaded it manually here again i can reproduce the behaviour:

```
c:\Users\AWSW\Documents\Arduino\libraries\ESPUI-master\src\ESPUI.cpp: In function 'String heapInfo(const __FlashStringHelper*)':
c:\Users\AWSW\Documents\Arduino\libraries\ESPUI-master\src\ESPUI.cpp:58:5: error: 'result' was not declared in this scope
     result += ESP.getFreeHeap();
     ^~~~~~

exit status 1

Compilation error: exit status 1
```

Switching back to the previuous ESPUI download from 15th of July fixes the problem.

The project is this one which runs on an ESP32 (Wemos D1 mini ESP32): 
https://github.com/AWSW-de/WordClock-16x16-LED-matrix-2023

Hope to help!

Kind regards and thanks in advance. :)

**Comment by d-a-v** [comment]
@AWSW-de @s00500 Sorry for this. I should have tested on esp32 too

**Comment by AWSW-de** [comment]
> @AWSW-de @s00500 Sorry for this. I should have tested on esp32 too

Everything is fine, no worries 😉
