### ISSUE TITLE
ESP32-S3 Compatibility?

### ISSUE THREAD

**Issue by FoxRunningFromCode** [s00500/ESPUI#244]
The feature request is to make the program compatible with ESP32-S3

Ive been trying for quite a few hours now to get it to work with the ESP32-S3-Wroom-1 but the chip keeps either halting or the program fails the "#if defined(ESP32)" parts of the code.

help, ive only been at this for 5 hours/3cups of coffee :)

**Comment by FoxRunningFromCode** [comment]
If it already is compatible, i would like to see an example code :)

**Comment by iangray001** [comment]
As I'm sure you know, the `#if defined(ESP32)` happens at compile time not runtime, so if you are finding that `ESP32` is not defined then something is wrong with your build process.

I don't have yet an S3 to test with until the slow boat from China makes its way to me, but it should all just work. I think.

**Comment by FoxRunningFromCode** [comment]
Woops you're right. Consider it a brain fart :)

I need to mention that my hardware is the raw module and not a board. Therefore the chances of me having a wrongly configured module, is fairly high.
(HW ESP32-S3-WROOM-1-N16R8)

My S3 dev board is still in the mail too.

Anyways I'm excited to hear if it works on your S3 chip.

**Comment by FoxRunningFromCode** [comment]
Lib IS compatible with ESP32-S3. I had defective hardware! Closing this thread due to issue not being an issue :)

Side note for anyone reading this: The ESP32-S3 seems to be unstable when using a wifi based libary, in arduino IDE as of writing this. The chip just straight up crashes and sometimes doesnt even get past first wifi conf. commands.

**Comment by iangray001** [comment]
How strange! Thnaks for reporting back.
