### ISSUE TITLE
Version 2.2.3 not availiable on PlatformIO

### ISSUE THREAD

**Issue by christian-heusel** [s00500/ESPUI#247]
**Describe the bug**
As the latest release does fix a compliation issue (https://github.com/s00500/ESPUI/issues/243) I wanted to included it in a project that utilizes ESPUI (see discussion here: Found when discussing https://github.com/dewenni/ESP_Buderus_KM271/issues/42) but the latest version cannot be found online.

**To Reproduce**
1. Go to https://registry.platformio.org/libraries/s00500/ESPUI/versions
2. See that there is no Version 2.2.3

**Expected behavior**
The latest version is published there, maybe this can be automated in the release process?

**Additional context**
Found when discussing https://github.com/dewenni/ESP_Buderus_KM271/issues/42

**Comment by s00500** [comment]
Uff, I should automate that at some point, I have started the publish now so I guess it will be there in the next few minutes

**Comment by christian-heusel** [comment]
Thank you for the very fast response and your awesome project ❤️
