### ISSUE TITLE
Captive portal

### ISSUE THREAD

**Issue by remcoNL** [s00500/ESPUI#25]
Is it possible to add a captive portal to the ESPUI interface?

**Comment by s00500** [comment]
Yes I definitely should do that

**Comment by nosoropoped** [comment]
this example don't work [https://github.com/s00500/ESPUI/blob/870e8a06a27c02074ccee4b0fec8b6a452ac3eb3/examples/gui/gui.ino](url)  
 error: invalid conversion from 'void (*)(Control, int)' to 'void (*)(Control*, int)' [-fpermissive]

the sketch above in arduino 1.8.12 and in earlier versions does not work,  please help

**Comment by s00500** [comment]
What processor are you using ? esp32 or esp8266 ?

**Comment by nosoropoped** [comment]
esp8266, Node MCU v3

**Comment by s00500** [comment]
Not really sure why you are using such an old version of the examples, make sure you are using the latest version of the libraries and the examples ! https://github.com/s00500/ESPUI/tree/master/examples

**Comment by nosoropoped** [comment]
I tried these examples, and tried again, but the connection to the page occurs only when entering the IP address manually (you have 192.168.1.1). Unfortunately, using captive portal does not work for me yet. When connecting to the ESP8266, nothing happens, the redirection of any request does not work, and there is no pop-up window with authentication on the phone.
Your library is great and I would really appreciate your help.
 P.S. All necessary libraries are installed.
thank

**Comment by s00500** [comment]
Ok, so this is not an easy to fix thing... and also not a issue of this library per se...
See the discussion here:
https://github.com/espressif/arduino-esp32/issues/1037

It hugely depends what OS you are using and how the captive portal is handled there.

Meanwhile opening the browser and opening any http:// address should work (No https!)
Try for example: http://captive.apple.com

Otherwise you can play with the captive portal examples included in the ESP8266 arduino core and try to figure out what works for you...

**Comment by nosoropoped** [comment]
yes, if you enter the html address exactly - everything works, but there is no pop-up window asking for pseudo-authentication. everything works well with the ESP8266WebServer library. I will try, thank you very much.

**Comment by nosoropoped** [comment]
Oh, it didn't work out for me (and not only for me) to launch the captive portal, I tried different versions of the IDE arduino, different boards: 8266, 32, but despite the DNS library, it is only easy to enter the page using manual input. Used examples from your library. Tell me what could be the problem. Thank you!

**Comment by s00500** [comment]
So... The problem might be the following: Captive portals in ios and android will only show up if all traffic is properly answered with a HTTP redirect. So even tough the dns server points traffic to the ESP you devices will still not show a popup as they do not get the correct redirect message back from the server... this could be implemented easily but I do not have time for it right now, prs are welcome

**Comment by nosoropoped** [comment]
Thank you, I will be very grateful if you can take the time to help. Your library is very popular in narrow circles.

**Comment by blackpressinc** [comment]
I was wondering if there was any update on this issue? I recently implimented a captive portal for ESPUI and it works on Android but does not seem to pop up on iOS.
