### ISSUE TITLE
Saving and uploading setting file to client

### ISSUE THREAD

**Issue by billyrudi** [s00500/ESPUI#258]
There is a way to save a setting file to a client and uploat it (spmartphone?)?

**Comment by iangray001** [comment]
You mean like a cookie? Not directly no. Maybe you can save settings that you need in the EEPROM of the ESP.

**Comment by billyrudi** [comment]
Yes I need to save eeprom parameters. Do you know how I can do?

⁣Ottieni BlueMail per Android ​

Il giorno 26 set 2023, 21:52, alle ore 21:52, Ian Gray ***@***.***> ha scritto:

**Comment by iangray001** [comment]
It's pretty easy in the Arduino framework.

https://www.aranacorp.com/en/using-the-eeprom-with-the-esp8266/

**Comment by billyrudi** [comment]
No, not this. I need to save settings from esp to client: a phone for example.

⁣Ottieni BlueMail per Android ​

Il giorno 26 set 2023, 22:01, alle ore 22:01, Ian Gray ***@***.***> ha scritto:

**Comment by iangray001** [comment]
I presume you intend for a mechanism for the ESP to read such data as well? Otherwise it would be useless.

The only ways a website can store persistent data on a client is either a cookie, or the Web Storage API. We haven't integrated either of these. It isn't impossible, I would imagine that something could be done by cloning the Time control that I added and using that model.

However, what are you actually trying to do?

**Comment by billyrudi** [comment]
I simply need to make a backup of the configuration parameters on a file on the phone and then send them to other esp32s with an upload without having to rewrite them

⁣Ottieni BlueMail per Android ​

Il giorno 26 set 2023, 22:16, alle ore 22:16, Ian Gray ***@***.***> ha scritto:

**Comment by iangray001** [comment]
But why do you have to store them in the phone and not in the ESP?

**Comment by billyrudi** [comment]
As I told you to store the parameters of an esp and replicate them on many others during configuration 

⁣Ottieni BlueMail per Android ​

Il giorno 26 set 2023, 22:22, alle ore 22:22, Ian Gray ***@***.***> ha scritto:

**Comment by iangray001** [comment]
If you are already sending "configuration data" to the clients from the ESP, then you already have it stored in the ESP. I don't understand why you need it stored on the client as well.

Maybe it is because I don't understand what you are trying to accomplish. Even if you could send "data" to the client, what are you trying to do with that?

**Comment by billyrudi** [comment]
See this

https://github.com/G6EJD/G6EJD-ESP-File-Server


⁣Ottieni BlueMail per Android ​

Il giorno 26 set 2023, 22:22, alle ore 22:22, Ian Gray ***@***.***> ha scritto:

**Comment by iangray001** [comment]
OK well...err...there you go. There's a way to store and load files from the ESP. If you ensure that you use ESPUI in non-SPIFFS mode the two libraries should probably coexist happily enough.

**Comment by billyrudi** [comment]
This is exactly why I need your help. I would like to integrate an analog mechanism with an upload and download button into espui. Is it possible? Would you help me?

⁣Ottieni BlueMail per Android ​

Il giorno 26 set 2023, 22:31, alle ore 22:31, Ian Gray ***@***.***> ha scritto:

**Comment by iangray001** [comment]
Well I don't know that library, but from a quick skim you will need to do a few things.

You can't have both on the same port. It looks like that library is hardcoded to serve on port 80. ESPUI is on 80 by default but we provide a way to change this:

```ESPUI.begin("ESPUI", nullptr, nullptr, 8000);  //Start on port 8000```

Upload a file to the library however the library says you should do it. I don't know what URL scheme it uses but determine the URL scheme and you can create a `Label` control which contains a link to the file which you can just click.

```ESPUI.label("A Label", ControlColor::Peterriver, "<a href='path/to/the/file/in/the/other/library'>Click me</a>");```

Something along those lines.
