### ISSUE TITLE
Just saying THANK YOU!!

### ISSUE THREAD

**Issue by mc-hamster** [s00500/ESPUI#259]
Hi @s00500!

Just want to say thank you for this amazing library. I searched far and wide for something to implement for the management interface of my art installation (https://github.com/NOVA-Cluster) and this did the trick with almost no fuss (Bug: https://github.com/s00500/ESPUI/issues/238).

![IMG_8594](https://github.com/s00500/ESPUI/assets/12804989/8a84b361-70f3-427f-9ca9-94d531784978)
![IMG_7762](https://github.com/s00500/ESPUI/assets/12804989/c909c03b-7c10-4fec-b66f-a05924c6f654)
https://www.youtube.com/watch?v=a3Wc-ahGum0

Coffee, incoming.

Cheers mate, keep up the good work!

**Comment by s00500** [comment]
Hey @mc-hamster, Thanks for showing your usecase, pretty cool stuff!!!
