### ISSUE TITLE
Dynamic Selector

### ISSUE THREAD

**Issue by billyrudi** [s00500/ESPUI#261]
Hi,
how i can create a dynamic selector with wifi ssid  networks?

thanks

**Comment by iangray001** [comment]
[This](https://github.com/s00500/ESPUI/blob/8f7cce59bfed1e85c8a76ca968681d115df0f6e9/examples/completeExample/completeExample.cpp#L113) shows an example of creating a selector with options from an array. Just fill this array with the visible SSIDs beforehand.

**Comment by billyrudi** [comment]
Thanks for answering.
.If I pass the string wifi.ssid(i).c_str() in your example the webpage crashed. Why?

⁣Ottieni BlueMail per Android ​

Il giorno 7 ott 2023, 21:50, alle ore 21:50, Ian Gray ***@***.***> ha scritto:

**Comment by iangray001** [comment]
Respectfully, "the webpage crashed" isn't really a bug report I can do much with.

Any error messages?
