### ISSUE TITLE
How to change buttontext on centerbutton from ESPUI.padwithcenter? 

### ISSUE THREAD

**Issue by SkyOneTwo** [s00500/ESPUI#262]
I want to change button text on center button from .padwithcenter [ESPUI.padwithcenter](https://github.com/s00500/ESPUI#buttonpad) dynamically. Can i add a icon instead text?

**Comment by iangray001** [comment]
Short answer, not easily. You'll have to edit `controls.js` [on this line](https://github.com/s00500/ESPUI/blob/8f7cce59bfed1e85c8a76ca968681d115df0f6e9/data/js/controls.js#L991) to change the OK to a [data URL](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs), and then recompile and redeploy as described in the README.

**Comment by SkyOneTwo** [comment]
Thanks for the quick reply. That helped!
