### ISSUE TITLE
Note for function argument type

### ISSUE THREAD

**Issue by telesyst** [s00500/ESPUI#270]
my be not bug

ESPUI.cpp row 1150

bool ESPUIClass::SendJsonDocToWebSocket(ArduinoJson::DynamicJsonDocument& document, uint16_t clientId)

"clientId" probably should be of type int.

**Comment by MartinMueller2003** [comment]
The ClientID is intentionally limited to 16 bits because we have a max number of 65535 objects we are allowed to create.
