### ISSUE TITLE
ElegantOTA and ESPUI

### ISSUE THREAD

**Issue by aiotech-pub** [s00500/ESPUI#280]
I have just written a test application using ESPUI and ElegantOTA together but using 2 different web servers, one running on port 80 and the other on port 8080. In my understanding ElegantOTA does not start the web server, instead it uses a web server used by the application and already running. So. it would be very useful a method on ESPUI class returning a pointer to the web server instance already started. I am quite sure it would work

**Comment by hagre** [comment]
I have found a nice working "example" for your problem: 
https://github.com/AOG-addendum/Dual-GPS
To test, initialy you have to acticate OTA in the GUI and reboot to use it

**Comment by Tuet** [comment]
This is the trick that works for me, just add the following in setup: ElegantOTA.begin(ESPUI.server);    // Start ElegantOTA

**Comment by MartinMueller2003** [comment]
> This is the trick that works for me, just add the following in setup: ElegantOTA.begin(ESPUI.server); // Start ElegantOTA

This is the intended and correct way to do this.

**Comment by aiotech-pub** [comment]
Ok, that's OK also for me, thanks guys.
