### ISSUE TITLE
ESPUI + httpUpdate error

### ISSUE THREAD

**Issue by Atorcha** [s00500/ESPUI#281]
**Describe the bug**
When I try to use the library httUpdate to keep my project updated I get an error. Sometimes it stopped whenit downloaded  a bit of file sometimesit stopped the downlad with an error
![Captura de pantalla 2024-01-03 224327](https://github.com/s00500/ESPUI/assets/4932853/33e0399a-0563-49ac-a5b2-7dc084658006)

![Captura de pantalla 2024-01-03 224355](https://github.com/s00500/ESPUI/assets/4932853/08c6378b-2333-4532-95ae-562f54e38084)
The second Is the maximum file I get

the code is in:  https://github.com/AnakinSpain/Anakino_Aquarium_ESPUI/tree/main

**Expected behavior**
It should be download the file and install it.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Atorcha** [comment]
Finally I could it with ESP32FOTA library 

[](https://github.com/chrisjoyce911/esp32FOTA/ 
)
I think that library is perfect for ESP32

**Comment by MartinMueller2003** [comment]
ESPUI does not do anything specific for OTA. I am not sure this should be a ticket in this project.

**Comment by Atorcha** [comment]
I could fix it with that library
