### ISSUE TITLE
Using the AsyncTCP.h ESPAsyncWebServer.h  to enable parallel use of WebSerial

### ISSUE THREAD

**Issue by StefanL38** [s00500/ESPUI#284]
Hi s00500,

your library is fantastic. Especially since autoupdating all clients work.

I tried to combine ESPUI with WebSerial from Ayush
https://github.com/ayushsharma82/WebSerial
but driving your

`  dnsServer.start(DNS_PORT, "*", apIP);
`
in parallel with
`AsyncWebServer server(80);
WebSerial.begin(&server);
`
Does not work. 
It seems logic to me that it does not work in parallel
This is the reason why I am asking how to modify your code to use the AsyncWebServer

best regards Stefan

**Comment by thomastech** [comment]
FYI, Port 80 is used by ESPUI's webserver port. So I suggest changing your Async port number to prevent conflicts.

- Thomas

**Comment by MartinMueller2003** [comment]
I got him sorted. The real issue is that he was starting TWO web servers when only one was needed. I had to expose the ESPUI web server to external code and that allowed Stefan to bind his Serial server to the ESPUI web server using a single port.
