### ISSUE TITLE
Change user and pass of GUI

### ISSUE THREAD

**Issue by Atorcha** [s00500/ESPUI#287]
Good job!!

I have tried to make user and pass of GUI a variable like string that you can save in NVS and although you update firm always is saved like SSID and PASS for example.

Has you consider to add this?

Thanks so much

**Comment by MartinMueller2003** [comment]
Are you asking if ESPUI should save data in NVM or on the file system? From what I can see, the library is config storage agnostic. The user is responsible for maintaining configuration information and updating the ESPUI object when things change. If ESP had a standardized way of storing config (like an android or ios APP) then we could do it.

**Comment by Atorcha** [comment]
Sorry maybe I didn't explain well. What I mean is "write" the user anda pass login into two strings.

ESPUI.begin("ESP32 web", "USER", "PASS");

by

String user = "nombre";
String pass = "contraseña";

ESPUI.begin("ESP32 web", user, pass);

**Comment by MartinMueller2003** [comment]
This will work

static String user = "nombre";
static String pass = "contraseña";

ESPUI.begin("ESP32 web", user.c_str(), pass.c_str());
