### ISSUE TITLE
horizontal alignment of switcher control

### ISSUE THREAD

**Issue by dewenni** [s00500/ESPUI#291]
I am struggling with a little design problem. If you place several controls next to each other, the switcher control is not on the same horizontal line as the other controls.

<img width="630" alt="image" src="https://github.com/s00500/ESPUI/assets/46074831/98322e9c-02aa-46c6-ace8-69baffcabb74">

I have also not yet managed to find the right css attribute with "setElementStyle" to change this.
Does anyone have an idea how to get the switcher control in line with the other controls?

**Comment by iangray001** [comment]
I would assume `margin-top: 10px;` would do it. Maybe `padding-top: 10px;`.

If you inspect the page in your web browser you can play with the styles to figure out what works then once you know, add it to your ESPUI code.

**Comment by dewenni** [comment]
Thank you very much for your quick response and the advice. Unfortunately, this does not solve the problem.
I have also played with the developer functions of the browser.
Here are the results of margin and padding

<img width="1119" alt="image" src="https://github.com/s00500/ESPUI/assets/46074831/e621d411-ae01-4b25-9124-705d9c23101d">
margin-top adds an additional space for all controls to the separator above

  
<img width="567" alt="image" src="https://github.com/s00500/ESPUI/assets/46074831/44446c50-ba4a-44a3-9d7f-a77a99e020a7">

padding-top enlarges the control

any other ideas?

**Comment by dewenni** [comment]
position: "fixed" instead of "relative" and additional margin-top:6px did the trick

<img width="393" alt="image" src="https://github.com/s00500/ESPUI/assets/46074831/6ae8bef2-d8ad-458b-89fe-fafe86265347">
<img width="570" alt="image" src="https://github.com/s00500/ESPUI/assets/46074831/c3a3f02e-ecc9-41ac-aa65-c6410bfd7b8c">

**Comment by iangray001** [comment]
Ha yes "fixed" will keep it in the same place in the viewport! `absolute` will anchor it from its normal position and then shift from there so that should work.
