### ISSUE TITLE
a "0" is displayed instead of the label o the button

### ISSUE THREAD

**Issue by borisgraell** [s00500/ESPUI#294]
i was working with grouped controls, specifically, group buttons, at some point the string label of the first button was displaying a zero instead of the label, later i found out it happened to the first tab, too.

**Comment by MartinMueller2003** [comment]
A sample of the code might help a bit. This has happened to me (not the zero but similar oddness). It usually means that you used a stack variable to initialize the string. since ESPUI uses pointers to strings, the strings need to remain in the calling code. I typically created a class wrapper around the controls to hold the strings I needed.

**Comment by borisgraell** [comment]
> A sample of the code might help a bit. This has happened to me (not the zero but similar oddness). It usually means that you used a stack variable to initialize the string. since ESPUI uses pointers to strings, the strings need to remain in the calling code. I typically created a class wrapper around the controls to hold the strings I needed.
> 

```
uint16_t tab1 = ESPUI.addControl( ControlType::Tab, "Control", "Control" ); 
  uint16_t tab2 = ESPUI.addControl( ControlType::Tab, "Memoria Drills", "Guardar Drill" );         // id 02
  uint16_t tab3 = ESPUI.addControl( ControlType::Tab, "Memoria bolas", "Guardar bola" );     // id 03
  uint16_t tab4 = ESPUI.addControl( ControlType::Tab, "PROGR", "PROGR" ); // id 04
```

this is how i use the tab feature

**Comment by MartinMueller2003** [comment]
All of those strings are stack variables. They do not have guaranteed persistence beyond the function scope.

This is how I do it:
    static const PROGMEM char BACKUP_TAB_STR      [] = "Backup";
    uint16_t    backupTab   = ESPUI.addControl (ControlType::Tab, "BACKUP", BACKUP_TAB_STR);

Doing it this way saves a ton of ram end ensures the names do not change.

**Comment by borisgraell** [comment]
thank you Mr Mueller! i was grouping a slider to a button, i fixed the problem by doing it backwards, grouping buttons to a slider.

but i do like your way better, it would be easier to translate the frontend. i will give it a try

**Comment by MartinMueller2003** [comment]
I normally create a label item and then group siders, input fields and buttons to the label.

**Comment by MartinMueller2003** [comment]
FYI: I have 9 tabs and up to 40 controls (some dynamically created and deleted) per tab. My smallest tab has 10 controles on it. Some of the improvements I have been making are due to having almost 300 controls on the UI.
