### ISSUE TITLE
beginResponse_P - Braking Change in mathieucarbou / ESPAsyncWebServer for ESP32 in release 3.0.2

### ISSUE THREAD

**Issue by hagre** [s00500/ESPUI#306]
see: https://github.com/mathieucarbou/ESPAsyncWebServer/pull/39

The beginResponse_P is only avaliable for ESP8266 at release 3.0.2

**Comment by mathieucarbou** [comment]
FYI, I've opened a PR to add back these methods as deprecated: https://github.com/mathieucarbou/ESPAsyncWebServer/pull/46
I hope to be able to merge it soon and release a new version of ESPAsyncWebServer.
