### ISSUE TITLE
Empty Controls 

### ISSUE THREAD

**Issue by headphones81** [s00500/ESPUI#4]
Hi , 
I installed dependencies , libraries - prepared FS 
But when connect to ESP I have blank page with Control Offline and no buttons/sliders etc....
Where Should I search the problem. It basically display only content from the Index.html without anything specified in gui.ino

**Comment by s00500** [comment]
Hm ok, on with processor are you? Can you run the prepare filesystem sketch and provide me with the serial output?

**Comment by s00500** [comment]
Also: check if you can load the individual files... are you using the version from github or the one from the library manager?

**Comment by headphones81** [comment]
I managed to find solution in index.html it was pointing to  zepto.js
instead to zepto.min.js

На 21.12.2017 14:57 "Lukas Bachschwell" <notifications@github.com> написа:

Also: check if you can load the individual files... are you using the
version from github or the one from the library manager?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/s00500/ESPUI/issues/4#issuecomment-353344193>, or mute
the thread

**Comment by s00500** [comment]
Oh yes... zepto does only exist in a minimized version... I will fix that thanks
