### ISSUE TITLE
error during compilation

### ISSUE THREAD

**Issue by erfan1383** [s00500/ESPUI#40]
Hi
I have recently used this library on windows 10 and Iwas quite happy with it
But i had to move my whole work to linux(parrot OS) and after installing arduino 1.8.7 and esp32 package, I started with gui example. It didn't work. Here's the error message:
Arduino: 1.8.7 (Linux), Board: "ESP32 Dev Module, Disabled, Default, QIO, 80MHz, 4MB (32Mb), 921600, None"

Build options changed, rebuilding all
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:259:27: error: field 'call' has incomplete type 'tcpip_api_call'
     struct tcpip_api_call call;
                           ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:259:12: note: forward declaration of 'struct tcpip_api_call'
     struct tcpip_api_call call;
            ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp: In function 'esp_err_t _tcp_output(tcp_pcb*)':
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:291:65: error: invalid conversion from 'err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)}' [-fpermissive]
     tcpip_api_call(_tcp_output_api, (struct tcpip_api_call*)&msg);
                                                                 ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:291:65: error: cannot convert 'tcpip_api_call*' to 'tcpip_api_call_data*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)'
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call' is incomplete
     struct tcpip_api_call call;
            ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp: In function 'esp_err_t _tcp_write(tcp_pcb*, const char*, size_t, uint8_t)':
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:307:64: error: invalid conversion from 'err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)}' [-fpermissive]
     tcpip_api_call(_tcp_write_api, (struct tcpip_api_call*)&msg);
                                                                ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:307:64: error: cannot convert 'tcpip_api_call*' to 'tcpip_api_call_data*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)'
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call' is incomplete
     struct tcpip_api_call call;
            ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp: In function 'esp_err_t _tcp_recved(tcp_pcb*, size_t)':
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:322:65: error: invalid conversion from 'err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)}' [-fpermissive]
     tcpip_api_call(_tcp_recved_api, (struct tcpip_api_call*)&msg);
                                                                 ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:322:65: error: cannot convert 'tcpip_api_call*' to 'tcpip_api_call_data*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)'
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call' is incomplete
     struct tcpip_api_call call;
            ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp: In function 'esp_err_t _tcp_connect(tcp_pcb*, ip_addr_t*, uint16_t, tcp_connected_fn)':
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:338:66: error: invalid conversion from 'err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)}' [-fpermissive]
     tcpip_api_call(_tcp_connect_api, (struct tcpip_api_call*)&msg);
                                                                  ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:338:66: error: cannot convert 'tcpip_api_call*' to 'tcpip_api_call_data*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)'
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call' is incomplete
     struct tcpip_api_call call;
            ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp: In function 'esp_err_t _tcp_close(tcp_pcb*)':
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:352:64: error: invalid conversion from 'err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)}' [-fpermissive]
     tcpip_api_call(_tcp_close_api, (struct tcpip_api_call*)&msg);
                                                                ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:352:64: error: cannot convert 'tcpip_api_call*' to 'tcpip_api_call_data*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)'
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call' is incomplete
     struct tcpip_api_call call;
            ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp: In function 'esp_err_t _tcp_abort(tcp_pcb*)':
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:367:64: error: invalid conversion from 'err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)}' [-fpermissive]
     tcpip_api_call(_tcp_abort_api, (struct tcpip_api_call*)&msg);
                                                                ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:367:64: error: cannot convert 'tcpip_api_call*' to 'tcpip_api_call_data*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)'
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call' is incomplete
     struct tcpip_api_call call;
            ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp: In function 'esp_err_t _tcp_bind(tcp_pcb*, ip_addr_t*, uint16_t)':
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:382:63: error: invalid conversion from 'err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)}' [-fpermissive]
     tcpip_api_call(_tcp_bind_api, (struct tcpip_api_call*)&msg);
                                                               ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:382:63: error: cannot convert 'tcpip_api_call*' to 'tcpip_api_call_data*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)'
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call' is incomplete
     struct tcpip_api_call call;
            ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp: In function 'tcp_pcb* _tcp_listen_with_backlog(tcp_pcb*, uint8_t)':
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:397:65: error: invalid conversion from 'err_t (*)(tcpip_api_call*) {aka signed char (*)(tcpip_api_call*)}' to 'tcpip_api_call_fn {aka signed char (*)(tcpip_api_call_data*)}' [-fpermissive]
     tcpip_api_call(_tcp_listen_api, (struct tcpip_api_call*)&msg);
                                                                 ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:397:65: error: cannot convert 'tcpip_api_call*' to 'tcpip_api_call_data*' for argument '2' to 'err_t tcpip_api_call(tcpip_api_call_fn, tcpip_api_call_data*)'
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:259:12: note: class type 'tcpip_api_call' is incomplete
     struct tcpip_api_call call;
            ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp: At global scope:
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:624:6: error: prototype for 'void AsyncClient::_dns_found(ip_addr_t*)' does not match any in class 'AsyncClient'
 void AsyncClient::_dns_found(ip_addr_t *ipaddr){
      ^
In file included from /root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:24:0:
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.h:84:10: error: candidate is: void AsyncClient::_dns_found(_ip_addr*)
     void _dns_found(struct _ip_addr *ipaddr);
          ^
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:946:6: error: prototype for 'void AsyncClient::_s_dns_found(const char*, ip_addr_t*, void*)' does not match any in class 'AsyncClient'
 void AsyncClient::_s_dns_found(const char * name, ip_addr_t * ipaddr, void * arg){
      ^
In file included from /root/Arduino/libraries/AsyncTCP/src/AsyncTCP.cpp:24:0:
/root/Arduino/libraries/AsyncTCP/src/AsyncTCP.h:164:17: error: candidate is: static void AsyncClient::_s_dns_found(const char*, _ip_addr*, void*)
     static void _s_dns_found(const char *name, struct _ip_addr *ipaddr, void *arg);
                 ^
Multiple libraries were found for "WiFi.h"
 Used: /root/Arduino/hardware/espressif/esp32/libraries/WiFi
 Not used: /home/user/arduino-1.8.7/libraries/WiFi
exit status 1
Error compiling for board ESP32 Dev Module.

**Comment by orithena** [comment]
This is definitely not a problem with the ESPUI library. Your ArduinoIDE or your ESP32 toolchain or your OS is not correctly set up. Nevertheless, here are a few pointers:

First: Never not login as root user unless you do system maintenance (and even that can be done from a user account using sudo and suchlike).
Second: I don't know ParrotOS, but it looks like a sandboxed system where you explicitely have to set permissions for each sandbox. It might be that the sandbox running the Arduino IDE does have enough permissions. Is this your first time to have your own linux system installed? If yes, then prepare for a steep learning curve. Sandboxed OSes do require some learning, even for a seasoned linux user.

**Comment by erfan1383** [comment]
about other examples, they all work.
well, it's more complicated. I could not use my PC, and the only option I had was that I use a flash memory on which I wrote the iso image and added a new partition(persistence). Because of those I just couldn't run arduino ide as a normal user(usb serial stuff...)-even I tried arduino playground solution for that, it doesn't work with live user- so again I had to install and run arduino as root.

And the only problem I had so far was with this AsynchTCP library(as you see all the erorrs are coming from that).

And I doubt I have the required library tcpip_priv.h required for AsyncTCP. I can't find that using locate command

**Comment by orithena** [comment]
For USB serial stuff, add your user to the group 'dialout' (or whatever group has write access to `/dev/ttyUSB0` -- which only exists if you actually have your ESP plugged in)... you can do that using `sudo adduser username dialout`, then re-login as user.

Any header files in `lwip` are part of the ESP32 libraries, as far as I know. They should have been installed when you installed the board into Arduino IDE. Did you install the board while running Arduino IDE as user, then later started the Arduino IDE as root? Then there's the problem: Boards and Libraries are installed into the user home.

Anyway, your problem is not related to ESPUI -- we also only use AsyncWebserver, which in turn uses AsyncTCP, which in turn uses the tcpip_priv.h from the board definitions (this file should be in `/home/user/Arduino/hardware/espressif/esp32/tools/sdk/include/lwip/lwip/priv/tcpip_priv.h`), but when you are running Arduino IDE as root, substitute `/home/user` with `root`.

**Comment by erfan1383** [comment]
So this problem is due to the OS itself.
The command `sudo adduser username dialout` does not work with my current user _user_.
Thanks for your help

**Comment by orithena** [comment]
It sure looks like there is a permission problem regarding the USB-serial port. This actually is standard on any Debian-based OS. So I'd recommend searching for "how to get write access to the USB-serial port on parrotOS" ... I'm actually surprised that that command didn't work (did you insert your actual username instead of the placeholder `username`? ... for a user named "user" it should be `sudo adduser user dialout` ... or if your OS does not grant you sudo rights, log in as root and use the command `adduser user dialout`).
