### ISSUE TITLE
My awesome library

### ISSUE THREAD

**Issue by thegoodhen** [s00500/ESPUI#41]
Hello, back when I didn't know about this project, I would start developing my own GUI for ESP.

Since I found out that it's still a bit different from yours, I continued the development. I believe it to be THE most feature-rich GUI library for ESP, since it already supports list boxes, text boxes, textareas, optional synchronization between clients, advanced methods of layout control and more. 

I still am working on it, but I will be releasing it soon under the MIT licence. Right now the examples work fine and it's more or less stable and working. Feel free to check it out and/or use any code from it!

https://github.com/thegoodhen/TGH-GUI

**Comment by s00500** [comment]
Ok thanks, fine
I hope you did not commit your actual wifi password in your examples (sync example line 42), otherwise that would be #Yolo (data->javascript.js line 21) 😉

This is anyway not an issue of this library

Thanks

**Comment by thegoodhen** [comment]
I did. Whoopsie! :D Gtg change the pass now... Thanks!

**Comment by orithena** [comment]
I'm leaning towards using https://github.com/tzapu/WiFiManager in example code. Reduces boilerplate and removes the chance of accidentally publishing the WiFi password. Downside is that it introduces a dependency (mitigated by the fact that that lib is available in the Arduino IDE library manager...).

**Comment by thegoodhen** [comment]
My library is powerful enough for me to be able to roll my own version of WiFiManager relatively simply, planning to give it a try soonish...
