### ISSUE TITLE
More than 8 User interface Elements not possible??

### ISSUE THREAD

**Issue by sadatusa** [s00500/ESPUI#43]
GREAT LIB! BUT...
I can only see maximum eight User interface Elements/Controls in my browser the 9th 10th and so on can not be seen...even the original example behave same.
Is this limitation of the lib?

**Screenshots**
![gui_scr_cap](https://user-images.githubusercontent.com/33061491/49699235-9d9f8480-fbf0-11e8-92e4-85369f3017ae.jpg)
r problem.

**Desktop:**
Windows 7 64bit
Firefox Quantum 63.0.3 (64-bit)
Chrome Version 71.0.3578.80 (Official Build) (64-bit)
and more others...same behavior.

**Comment by s00500** [comment]
Hey, thanks for the report, are you running ESPUI on ESP8266 or ESP32 ? I will try to replicate this as soon as possible

**Comment by sadatusa** [comment]
ESP8266

**Comment by s00500** [comment]
Hey, so I could not replicate this at all, I tried it in chrome and Firefox and on my iphone, I used the gui example without any changes, everything works as expected, I can see the sliders, text fields and numberinput


 what version of ESPUI are you using? how did you install it? (Lib manager, platformio, download from github) How did you upload it? (arduino IDE, platformio)

Did you use the normal begin (recommended) or SPIFFS?

**Comment by sadatusa** [comment]
Okay..
I used arduino IDE, 
install it? (download from github)
upload it? (arduino IDE)
begin (recommended) or SPIFFS? tested both.

**Comment by s00500** [comment]
strange, did you use the exact gui example or did you make changes to the code? when did you download it? what version of esp8266 core are you using? what version of espasynctwebserver are you using?

**Comment by douganzardo** [comment]
the same for mi

**Comment by douganzardo** [comment]
ESP core 2.4.2

**Comment by s00500** [comment]
Ok I found the issue, it is due to a change in ESPAsyncWebserver and can be found in this commit : https://github.com/me-no-dev/ESPAsyncWebServer/commit/bed4146ec647fd1cdfd1d2485724369c92cab8e6

**Comment by s00500** [comment]
Ok this issue should be fixed on master right now, you can test the masterbranch with the latest version of ESPAsyncWebserver, there will be a 1.6.1 release soon that will include the fix

**Comment by sadatusa** [comment]
Thanks dear, really appreciate you work. Thanks again
Sadat
