### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by ghoeffner** [s00500/ESPUI#44]
**Is your feature request related to a problem? Please describe.**
No problem. We're using a ESP with ESPUI at a hackerspace and would like to set a password 👍 

**Describe the solution you'd like**
Just a basic auth where you can give username and password would be sufficient!

**Describe alternatives you've considered**
Well, alternative would be a full pw auth... but that's a little bit overkill - and you still want the lib to fit on all controllers ;)

**Comment by s00500** [comment]
Hm yes that could be a good aditional feature, I will see what I can do

Are you coming to congress? (35C3) Cause I will be there and I am always interested in what this library is used for 😃

**Comment by ghoeffner** [comment]
Hey @s00500 , can't make it this year ;)
It's being used to control access to "Mr. Coffee" at the [Munich Maker Lab Munich](https://munichmakerlab.de/) ;)

![mr-coffee-picture](https://user-images.githubusercontent.com/1123412/50442508-84d8e380-08ff-11e9-8c61-9ad899ee8112.jpg)

**Comment by s00500** [comment]
Really cool !!! 
Ok so the quickest and easiest thing to implement is using basic auth, but I probably don't have to tell you about why this is anywhere near to secure without proper HTTPS, this again could make serious troubles, especially on the ESP8266...

Do you have any additions to that? otherwise I'll implement it today, after I fixed #43

**Comment by ghoeffner** [comment]
@s00500 I think that we both know that it's not a proper security measure for anyone who can sniff traffic. However, I think it's sufficient for most things that you don't want people to "accidently" mess with. If you're running medical devices or anything sensitive on a ESP8266, you're doing something fckd up anyway. 

However, the documentation should probably state a warning that this is not a security measure sufficient for devices in untrusted networks or public access. 

Let me know once you have implemented it and we will test it over here 👍

**Comment by s00500** [comment]
Added to master, use    
`ESPUI.begin("ESPUI Control", "myuser", "mypassword");`

Please test (I have only tested it with begin on the ESP8266, not yet with beginSpiffs, although it should also work)

If this solved the issue please close, and I will do a new release

**Comment by ghoeffner** [comment]
Works great with ESPUI.begin! Just as expected. Thanks @s00500!

**Comment by ghoeffner** [comment]
Actually there seems to be a bug, the password auth on iPhone chrome & safari seems to be broken. I don't know how to debug that exactly, but after logging in ESPUI says "Error No Connection" and the screen stays blank without controls.

**Comment by s00500** [comment]
Hm might have to do something with the websocket auth....

**Comment by ghoeffner** [comment]
> Hm might have to do something with the websocket auth....

I'd assume so. Not exactly sure how to debug that. It's working just fine on the desktop!

**Comment by s00500** [comment]
Ok so this is really stupid.... but apperently **WS basic auth** is not supported in safari

See here: https://bugs.webkit.org/show_bug.cgi?id=80362

I was not able to find a workaround, so I will remove ws auth, but leave a define to enable it if needed.

The define is WS_AUTHENTICATION and it is false per default

**Comment by ghoeffner** [comment]
@s00500 I spontanously went to 35c3! Let's meet :)

**Comment by s00500** [comment]
SIP 6565
