### ISSUE TITLE
Multiple web pages

### ISSUE THREAD

**Issue by anuragmishra81** [s00500/ESPUI#45]
This is an excellent library. Thank you for all the wonderful features.

I created a webpage using the library and it works good. However I am not sure how to create multiple pages. Example, one page where I can have all the buttons etc to control the devices and additional page for configuration. 
Could you kindly guide on how to create multiple pages.

**Comment by orithena** [comment]
Sorry, we don't have that use case covered (yet).

I'll mark it as a feature request for the time being.

**Comment by eringerli** [comment]
Check out my pull request, I added a tabbed view. This should help organizing the controls into different pages.

**Comment by s00500** [comment]
@eringerli `s code will be in next release, closing
