### ISSUE TITLE
List box or popup menu list

### ISSUE THREAD

**Issue by sorriso93** [s00500/ESPUI#46]
**Is your feature request related to a problem? Please describe.**
Hello it would be great to have a listbox or pop menu to chose for example from a city list (i.e. for weather station) or other parameters to be configured

**Comment by s00500** [comment]
Ok, can you provide us with some ideas of how this could look and how the functions should look that generate the control?

**Comment by sorriso93** [comment]
Hello, sure, below some images
https://docs.oracle.com/javaee/5/tutorial/doc/figures/jsfpage-selectone.gif
below html code for menu,
https://html.com/tags/select/

**Comment by s00500** [comment]
Ah ok no, that was not what I meant... I meant how you imagine the ESPUI function call to look like.

I have the feeling that the calls to ESPUI.button( ... .label ... and so on are getting longer and longer
Do you have an Idea how the config for the ESPUI.select( could look like? Should we pass it a String Array? and should it return the string or the index in the callback?! These questions need to be solved

**Comment by anuragmishra81** [comment]
If I may suggest... 

Assuming ddl is dropdown-list

ESPUI.ddl(ctrl name, "csv list values", ADD/REM, TYPE)  //creates list and adds or remove items. TYPE describes various ddl as shown in image shared by sorriso93. For REM operation TYPE is not required


String a=ESPUI.ddl  //returns csv selected.

**Comment by ghoeffner** [comment]
I think it would make most sense to init the ESPUI.choser("Control Name", Type = checkbox,radio,list,dropdown) and then
ESPUI.additem("Control Name", "Item Name", functioncall(?))
ESPUI.removeitem("Control Name", "Item Name")

**Comment by sorriso93** [comment]
Agree with last proposal. Maybe the chooser function could be ideal to have it as a callback...

**Comment by ghoeffner** [comment]
> Agree with last proposal. Maybe the chooser function could be ideal to have it as a callback...
I guess you could have the callback set in the ESPUI.choser function as well.

**Comment by s00500** [comment]
Yep as always, and then return the id and the string...

I will probably have to rething the way controls are stored in menory and how callbacks are handeled a little bit...

**Comment by eringerli** [comment]
I just added a pull request to enhance the API, so you can use (amongst other things, the diff us HUGE) unified controls (I cut a lot of redundant code out) with parents. I haven't gotten to add a dropdown control, but it is definitvely on my todo list, as I need them in my project. I think, I can add them in the next few days, so check the repository out.

The way to add them would be really simple: add a select-control and then add all the options to it, referencing the select. You can even add to all of them a callback, so reacting on user input is also simple. The same is now possible with the tabbed view: there you add a tab, then the different controls with a reference to it.

**Comment by s00500** [comment]
Looks cool, have a stressy week ahead but I will look through it in the next days and test it

**Comment by eringerli** [comment]
Now there is support for dropdown-lists: #48

**Comment by sorriso93** [comment]
thks I will test it as soon as I have time

**Comment by Bavilo** [comment]
I would also love to have dropdown lists!

**Comment by s00500** [comment]
@eringerli `s changes will be in the 2.0 release going out soon, closing
