### ISSUE TITLE
Black color for UIs

### ISSUE THREAD

**Issue by roboticafacil** [s00500/ESPUI#47]
**Describe the bug**
COLOR_NONE has the same definition value as COLOR_ALIZARIN.

**To Reproduce**
If you create an UI with COLOR_NONE or COLOR_ALIZARIN has the same behaviour.

**Expected behavior**
I expected to be a 'black' or dark color, which should be the default color for a white background.

**Comment by s00500** [comment]
Released in 1.6.2
