### ISSUE TITLE
regular crash with "gui" example

### ISSUE THREAD

**Issue by tx73github** [s00500/ESPUI#5]
Merry Christmas,
I experience regular crashes, on 8266 E12-F.
I rolled back to ESPUI packetmanager version 1.40 version of "GUI" example and initialised filesystem with prepareFS successfully. 
After a short while I get crashes:

Exception (28):
epc1=0x4020acbc epc2=0x00000000 epc3=0x00000000 excvaddr=0x0000000c depc=0x00000000

ctx: cont 
sp: 3fff08b0 end: 3fff0c80 offset: 01a0

>>>stack>>>
3fff0a50:  3fff2c14 0000001d 00000001 40211634  
3fff0a60:  00000020 00000000 3fff3724 4020ad3a  
3fff0a70:  3fff2c14 0000001d 40209d84 402128d0  
3fff0a80:  3ffef910 3ffef910 00000001 4020ad5e  
3fff0a90:  3fff0b98 3ffef910 00000001 4020708e  
3fff0aa0:  3fff0aa8 0000001d 3fff0ad0 00000001  
3fff0ab0:  3ffef910 00000006 3fff0ad0 4020815c  
3fff0ac0:  3ffe8a98 3fff0ad0 000000c8 0000003a  
3fff0ad0:  3fff0ac0 3fff0ad8 3fff0ae8 3ffe88e8  
3fff0ae0:  00000004 00000007 3fff0af8 3ffe88f0  
3fff0af0:  00000004 00000001 00000000 3ffe88f8  
3fff0b00:  00000002 3fff0b08 3fff0036 3ffe88f0  
3fff0b10:  00000002 3fff0b18 31353932 40003231  
3fff0b20:  00000000 3ffe88f8 00000002 3ffefb6c  
3fff0b30:  00000010 3fff0bc0 00000000 4010053d  
3fff0b40:  00000010 3fff0bd0 00000000 4010053d  
3fff0b50:  00000003 11970471 00000000 00000000  
3fff0b60:  00000010 3fff0bc0 3fff0bc0 40210d10  
3fff0b70:  3ffe85bc 0000000a 3fff0bc0 40210d5f  
3fff0b80:  3ffefb6c 000002ea 000002ea 4010020c  
3fff0b90:  3fff0bf0 3ffef910 3fff2c14 0000001f  
3fff0ba0:  0000001d 3fff2bec 0000001f 0000001d  
3fff0bb0:  3ffefb6c 0000033a 00000006 402070e0  
3fff0bc0:  ffffffff 00000000 00000000 40210e54  
3fff0bd0:  3fff0c4c 00000001 3ffef910 ffffffff  
3fff0be0:  00000001 3fff0c40 3ffef910 4020826f  
3fff0bf0:  3fff2e6c 0000000f 0000000a 40210d5f  
3fff0c00:  3ffefb6c 000002ea 3fff0c40 40210d91  
3fff0c10:  00000001 3ffef910 3fff0c40 40210de2  
3fff0c20:  3ffe85bc 00000000 3fff0c50 3ffefc4c  
3fff0c30:  3ffef904 3ffef910 3ffef900 40206eaf  
3fff0c40:  3fff2e54 0000000f 0000000a 00000000  
3fff0c50:  00000000 00000000 00000001 4021178d  
3fff0c60:  3fffdad0 00000000 3ffefc45 402117b8  
3fff0c70:  feefeffe feefeffe 3ffefc60 40100718  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,7)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3de0c112
~ld
⸮
IP address: 192.168.4.1
UI Initialized

Tried with 80mhz and 160mhz.
Regards //t

**Comment by s00500** [comment]
Hm.. esp8266 support is still not really tested at all... I will see what I can do...

**Comment by tx73github** [comment]
Thanks, to get the current version to compile I needed to undo your FS patch (see comment) but crashes keep coming. It seems to be related to a client reconnecting to the webinterface.

**Comment by tx73github** [comment]
Hi, I tested the example in station mode to exclude wifi reconnection issues. Crash confirmed. Point a webbrowser to the IP, press a button and then reload the page in the webbrowser. Either immediately or after first press the 8266 will crash as above.

**Comment by s00500** [comment]
ok I will test that as well, the filesystem patch should be fixed in 1.4.2

**Comment by tx73github** [comment]
confirmed, 1.4.2 prepare FS and gui example now compile again and works as expected, modulo the crash after reload.

**Comment by s00500** [comment]
Ok sry for the silly bug, and thanks for reporting, I rebuilt the textThem method, the problem is actually that something like this does not exist in the ESPAsyncWebserver library, and the array of connected websocket clients is priovate in the library.... This is the explaination why the current implementation is still a little silly, but it does what it should do. A proper solution would be a pull request to the Webserver library to properly implement a textAllExluding function.

Can you confirm the fix?

**Comment by tx73github** [comment]
Confirming fix ! 
One suggestion, can you include the SPIFFS Editor into ESPUI or document how to set it up in the sketch.
Many thanks
