### ISSUE TITLE
FW Upload Widget

### ISSUE THREAD

**Issue by Gerfunky** [s00500/ESPUI#50]
**Is your feature request related to a problem? Please describe.**
For projects that use your Lib it would be cool  if its possible to update  the Firmware over the webpage. So it possible to update the FW without having to compile. Makes distributing new FW a lot easyer and usable by non Programmers. 

**Describe the solution you'd like**
Make a new Widget with button that opens a file explorer to select a file to upload.

**Describe alternatives you've considered**
Programming it and Making a Pull request. But since i dont know with the new changes comming in/ API changes when to start with this. And I cant do the WEB part thats why im starting with your library. 
Or Asking you to create a callback where we can configure the Webserver or make the webserver Public.
So that it possible to add more stuff/pages to the webserver without having to write  stuff into the library.  

**Additional context**
My Led project TinyPixelMapper need a basic web UI and thats why im looking into your Library.

**Comment by shaurya0406** [comment]
Something like this would be awesome.
https://github.com/billz/raspap-webgui

**Comment by s00500** [comment]
hm... I am not sure about this, first of all you still need to compile firmware, anyway what you want to do ;-)

And I think using ArduinoOTA on a different port should be good enough... Not so sure about a file upload....
