### ISSUE TITLE
option to rotate sliders

### ISSUE THREAD

**Issue by just-jason** [s00500/ESPUI#54]
**Is your feature request related to a problem? 
using the sliders to control features like direction / speed, or elevation / rotation it is not very intuitive if both sliders have the same orientation

**Describe the solution you'd like**
The ability to rotate the sliders either verticaly or horizontally. This would be very good for things like pan / tilt camera platforms or remote controlled car projects

**Comment by s00500** [comment]
true that would be a cool thing

**Comment by iangray001** [comment]
Initial support being added in [this pull request](https://github.com/s00500/ESPUI/pull/152/commits/576890e033406de7a37b4f788cf25a3abfd3790a).
