### ISSUE TITLE
Multiple buttons using the same container

### ISSUE THREAD

**Issue by Bavilo** [s00500/ESPUI#57]
Hi,

it would be nice to have lets say 6 buttons which are nested inside the same container. The container could have a title like: "Dimming" and there would be 6 buttons with different dimming levels.

It would look cleaner than having 6 individual buttons which all have the title "Dimming".

Thanks!

**Comment by s00500** [comment]
Have you tested the Slider for something like this ?

**Comment by Bavilo** [comment]
A slider works fine for this as well. A Button group would be a cool feature though

**Comment by qroac** [comment]
I would further love to be able to combine multiple simple controls (like text, label, button) in one container.

This would enable me to build informative controls with action elements in small logical groups.

**Comment by shrikant2002** [comment]
yeah same for me it would be great to have a group of buttons or other similar components or may be different components too!

**Comment by s00500** [comment]
As for now it is very unlikely that I will work on changing the UI structure, if anyone wants to have a go though please submit a PR and I am happy to take a look at it
