### ISSUE TITLE
ArduinoJson Migration from 5 to 6 / Version conflicts using other Frameworks

### ISSUE THREAD

**Issue by Buzze11** [s00500/ESPUI#58]
Is there a plan to migrate the espui framework to ArduinoJson Version 6? I have conflicts using other Frameworks which require already Version 6.

An update from the sources of ESPUI to ArduinoJson v6 will be perfect.

Here you can find the migration documentation:
*ttps://arduinojson.org/v6/doc/upgrade/

**Comment by s00500** [comment]
It has already been done on the 2.0.0 branch, that will be released once I finished the rest of its todolist

**Comment by Buzze11** [comment]
Thanks a lot for the fast reply. The I will have to wait for the release. 
BR

**Comment by s00500** [comment]
this is done, release will be done soon
