### ISSUE TITLE
Joined existing network, webpage timeouts

### ISSUE THREAD

**Issue by pablopeu** [s00500/ESPUI#59]
If I create a custom AP with the unmodified example sketch, I can access all the controls with the provided example. Beautiful.
If I change the setup() commenting out the AP code and uncommenting the join existing network code it connects to the network, displays the assigned IP, shows "UI Initialized" but the webpage at this address timeouts, using my mobile phone or chrome on the desktop.
Tried with and without HTTP BasicAuth, same results.

[edit] forgot to add, ESP8266 on Arduino 1.89 IDE

**Comment by s00500** [comment]
hm ok, I could not really reproduce this, I am using firefox and I did clear my cache as well a few times, I realized that the connection timeout is too short though in the bbeginning, so sometimes it did not connect properly...

**Comment by s00500** [comment]
Please report if you can still reproduce this issue, otherwise its closed
