### ISSUE TITLE
Switchable Slider Behaviour in 2.0

### ISSUE THREAD

**Issue by 3gyptian** [s00500/ESPUI#60]
PlatformIO all boards/libraries updated to latest (except ArduinoJson == 5.13.4)
ESP32 DOIT DEV KIT V1 

Using example code the web server crashes after continually moving one of the sliders for ~5-20 seconds.  This only occurs when connecting to an existing wifi network.  The web server does not appear to ever crash when running example code configured as a wifi access point (ie: when running example exactly as posted).  

Placing print statements in the 5 second 'flip switch' routine shows the code is still running .. only the web interface is down.  As a test I found that if I force a restart of the WiFI session every minute the web server comes back online if it was hung prior to the wifi restart.

WiFi.disconnect();
WiFi.begin(ssid, password);

This occurs when connecting with chrome and firefox browsers on both mac and iOS.

**Comment by s00500** [comment]
can you test this with the 2.0.0 Branch ?

**Comment by 3gyptian** [comment]
Yes 2.0.0 test out a lot better.  I'm only experiencing very occasional web interface hangs now when doing a lot of slider controls on chrome browser on my laptop. And even then only on my code (but not from the chrome browser on my phone).  The sample code seems to hold up solid on 2.0.0 for me.   

I suspect the improvement here comes from the change in behaviour in 2.0.0 where the slider value only updates when the slider is released in the gui?  I'm using multiple sliders to tweak brightness, hue's and other settings on a long string of LED's and the realtime slider update worked really great with the previous version when running in AP mode.  Is there a way in version 2.0.0 for my code to optionally enable the slider behavior restored to real-time as it was before for times I run my code in AP mode again?  

And do you have any ideas suggestions for the odd time the web interface still hangs up for me? As on the previous version when the web interface hangs up the whole device has virtually dropped off the network and can't be pinged until it's power cycled or if my code bounces the wifi connection.  I'm thinking of adding a watchdog routine where it will disconnect and restart  the wifi connection in the event it can't ping the router for an extended period. Is there a more elegant way to catch this condition?

Anyway -- I really appreciate what you've done here ... it's a really powerful yet simple interface to add to one's project.  Well done and thank you!

**Comment by s00500** [comment]
We should have switchable slider behavior... Let me see what I can do...

**Comment by s00500** [comment]
In version 2 set the property sliderContinuous to true before calling ESPUI.begin

```
  ESPUI.sliderContinuous = true;
  ESPUI.begin("ESPUI Control");
```
