### ISSUE TITLE
[1.8.9] Multiple libraries were found for "WiFiUdp.h"

### ISSUE THREAD

**Issue by mnemocron** [s00500/ESPUI#61]
I cannot get the `gui` example sketch to compile for Feather HUZZAH board.
The compiler fails with the following error message:

```
C:\Users\simon\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ArduinoOTA\ArduinoOTA.cpp: In member function 'void ArduinoOTAClass::_runUpdate()':

C:\Users\simon\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ArduinoOTA\ArduinoOTA.cpp:281:3: error: 'stopAll' is not a member of 'WiFiUDP'

   WiFiUDP::stopAll();

   ^

Multiple libraries were found for "WiFiUdp.h"
 Used: C:\Program Files (x86)\Arduino\libraries\WiFi
 Not used: C:\Users\simon\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2\libraries\ESP8266WiFi
exit status 1
Error compiling for board Adafruit Feather HUZZAH ESP8266.
```

I tried to include the correct WiFiUdp.h using a hardcoded absolute path. But this fails at the next include instance `include/slist.h`

**Additional Info**
- Fresh install of Arduino 1.8.9 (also deleted the AppData/Arduino15 folder)

Installed Libraries
- Adafruit_NeoPixel
- ArduinoJson (5.x)
- ESPAsyncTCP
- ESPAsyncWebServer
- ESPUI
- ESP_Async_E1.31

**Comment by s00500** [comment]
Since this is a compile issue these issues should not be related. Try to remove the code responsible for MDNS from the example and test again, you can also try to use the 2.0.0 Branch and see if you can compile that

**Comment by mnemocron** [comment]
I tried it in VS Code using Platform IO and it works perfectly.
I don't know where the problem in Arduino is coming from, especially since I reinstalled it.

Not sure if it is helpful or if you can close the issue.

```
Dependency Graph
|-- <ESP8266WiFi> 1.0    
|-- <DNSServer> 1.1.1    
|   |-- <ESP8266WiFi> 1.0
|-- <ESPUI> 1.6.3        
|   |-- <ESP Async WebServer> 1.2.2
|   |   |-- <ESPAsyncTCP> 1.2.0
|   |   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <Hash> 1.0
|   |   |-- <ArduinoJson> 5.13.4
|   |-- <ArduinoJson> 5.13.4
|   |-- <ESP8266mDNS> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESPAsyncTCP> 1.2.0
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoOTA> 1.0
|   |   |-- <ESP8266mDNS> 1.2
|   |   |   |-- <ESP8266WiFi> 1.0
|   |   |-- <ESP8266WiFi> 1.0
```

**Comment by orithena** [comment]
I think it's related to Arduino IDE choosing the wrong library location. See https://forum.arduino.cc/index.php?topic=488732.0 for a discussion of that problem (including a method of selecting the library to use by path).

**Comment by s00500** [comment]
can we confirm this is solved with 2.0 ?

**Comment by mnemocron** [comment]
Using latest Software
- Arduino 1.8.10
- esp8266 2.6.3
- ESPUI 2.0.0

compiled `gui.ino` for board "Adafruit Feather HUZZAH ESP8266" works for me.

```
Done compiling.
Sketch uses 377164 bytes (36%) of program storage space. Maximum is 1044464 bytes.
Global variables use 31300 bytes (38%) of dynamic memory, leaving 50620 bytes for local variables. Maximum is 81920 bytes.
```

**Comment by s00500** [comment]
sweet, closing
