### ISSUE TITLE
sender.value can be stored in a variable?

### ISSUE THREAD

**Issue by cosminiq** [s00500/ESPUI#62]
Hi. i have a little problem !
I want to store **sender.value** text writen in TextCall, in to a variable, and after that, to print on a LCD cristal 20x4.
I don't know how to store sender.value in a variable (ex. string).
Can you help me?

ps. Sorry for my bad english, i'm not native

**Comment by s00500** [comment]
You should be able to directly output sender.value to the display. If the function for the display requires a char array pls check how to convert the string class to a char array

```
char charBuf[50];
sender.value.toCharArray(charBuf, 50) 
```
