### ISSUE TITLE
[2.0] More than 31 elements do not work

### ISSUE THREAD

**Issue by doppelgrau** [s00500/ESPUI#63]
**Describe the bug**
If defining more than 31 controls (reasonable with a few tabs, especially if you use min/max/step for numeric controls and pulldowns), the 32 control is rendered without color and parent. (At least in my setup https://github.com/doppelgrau/esp32-aog/tree/Cleanup - with shorter titel maybe it would happen later).

**To Reproduce**
Create GUI with lots of controls and find items missing.
Use the web dev inspection of your browser and see that in the first websocket message not all controls are transmitted.

**Expected behavior**
all controls are transmitted.

**Screenshots**

**Additional context**
Problem seems somehow related to the serialization of the controls, increasing DynamicJsonDocument document(4000) from 4000 to 8000 in ESPUIClass::jsonDom(AsyncWebSocketClient *client) did "solve" the problem.
Since I'm planing to add more controls (especially some pulldowns with more entries), I'm not sure if that's the way to go.

**Comment by s00500** [comment]
About how many controls are you speaking roughly ?

**Comment by doppelgrau** [comment]
A rough guess will be a total around 150-250. Most of them Puldown-Entries (and even there some with the same values. E.g. for different functions which IO-Pin to use).
Rough estimate (using some tabs) about 40 "visible" controls, the rest are pulldown-menu entries and/or min/max for number-entries.

Happy holidays.

**Comment by s00500** [comment]
Are you by any chance at 36c3 ? =D Otherwise the option I can enable is to make the Document size adjustable for extreme cases like yours, what do you think ?

**Comment by doppelgrau** [comment]
Yes, I'm at the 36C3 (DECT 5066 - in about 2h again on the fair ground).

**Comment by s00500** [comment]
Default limit for initial gui json has been raised to 8000, additionally the size has been added as a configurable parameters, eg:

```
  ESPUI.jsonUpdateDocumentSize = 2000;
  ESPUI.jsonInitialDocumentSize = 9000;
  ESPUI.begin("ESPUI Control");
```
