### ISSUE TITLE
ESPUI as Class Member?

### ISSUE THREAD

**Issue by kokospalme** [s00500/ESPUI#67]
Hello guys!
Thank you for this very nice project!
I have an issue putting the ESPUI-Library into my existing project, which works within its own Library.
I have something like this:

```
class Myclass{
  void setupUI(); //setup ESPUI...
  void doStuff( Control* sender, int value ); //do something
}

void Myclass::setupUI(){
  /*** add a select object to UI ***/
  uint16_t select = ESPUI.addControl( ControlType::Select, "Select:", "", ControlColor::Alizarin, tab1, &doStuff ); //<-- this causes an Error
  ESPUI.addControl( ControlType::Option, "Option1", "Opt1", ControlColor::Alizarin, selectMode );
  ESPUI.addControl( ControlType::Option, "Option2", "Opt2", ControlColor::Alizarin, selectMode );
  ESPUI.addControl( ControlType::Option, "Option3", "Opt3", ControlColor::Alizarin, selectMode );

  ESPUI.begin("ESPUI Control");
}

void Myclass::doStuff( Control* sender, int value ){
  
}
```

It causes an compiling Error like:

` error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.`

Is it even possible to work with ESPUI withing an existing class? I don't understand why I can put a function as pointer to the addControl-method in the .ino-file but not within my class? 
Can anyone help me or has the same problem?

Thank you really much

**Comment by s00500** [comment]
The function you are trying to add as a callback is non-static, that means since there can be several instances of your class the compiler can not be sure on what instance you want to call the function on, this is why it is illegal

**Comment by kokospalme** [comment]
thanks for the quick reply!
