### ISSUE TITLE
Is it possible to dynamically remove controls?

### ISSUE THREAD

**Issue by nen777w** [s00500/ESPUI#68]
Is it possible to dynamically remove controls?
For example, remove some items in Select?

We can remove controls form the controls list. Like that:
But how to send a request to update the page?

```
bool ESPUIClass::remControl(uint16_t id)
{
  if(nullptr == this->controls) return false;

  Control * it = this->controls;
  
  if(id == it->id) {
    this->controls = it->next;
    delete it;
    //need something for update the page
    return true;
  }

  Control * it_next = it->next;
  while(nullptr != it_next && id != it_next->id) {
    it = it_next;
    it_next = it_next->next;
  }

  if(nullptr != it_next) {
    it->next = it_next->next;
    delete it_next;
    //need something for update the page
    return true;
  }
  
  return false;
}
```

**Comment by nen777w** [comment]
Update: I implemented it as...
```
//h
#define UI_RELOAD ControlType::Reload
//cpp
bool ESPUIClass::remControl(uint16_t id, bool reload_ui)
{
  if(nullptr == this->controls) return false;

  Control * it = this->controls;
  
  if(id == it->id) {
    this->controls = it->next;
    delete it;
    if(reload_ui) {
      reload();
    }
    return true;
  }

  Control * it_next = it->next;
  while(nullptr != it_next && id != it_next->id) {
    it = it_next;
    it_next = it_next->next;
  }

  if(nullptr != it_next) {
    it->next = it_next->next;
    delete it_next;
    if(reload_ui) {
      reload();
    }    
    return true;
  }
  
  return false;
}

void ESPUIClass::reload()
{
  int tryId = 0;

  for (int count = 0; count < this->ws->count();) {
    if (this->ws->hasClient(tryId)) {
      ESPUI.jsonReload(this->ws->client(tryId));
      count++;
    }
    tryId++;
  }
}
```
on js side:
```
 var handleEvent = function(evt) {
.....
 case UI_RELOAD:
	window.location.reload();
	break;
```

**Comment by s00500** [comment]
You could make a pull request and we could look into merging it

**Comment by nen777w** [comment]
ok

**Comment by DeeJayMX** [comment]
Does this implementation is done ?

**Comment by nen777w** [comment]
> Does this implementation is done ?

Sorry. I completely forgot about that. I will make the Pool Request today.

**Comment by nen777w** [comment]
> You could make a pull request and we could look into merging it

I can't make pull request:
 git branch --set-upstream-to=origin/<branch> rem_control

ERROR: Permission to s00500/ESPUI.git denied to nen777w.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Should I use a specific branch for it?

**Comment by DeeJayMX** [comment]
Do you have another repo for that ?

**Comment by s00500** [comment]
@nen777w please fork the repository first using the fork button, then push a branch on your own fork of the repo and then make a pull request to this repository again, this is how it works on github ;-)

**Comment by nen777w** [comment]
> @nen777w please fork the repository first using the fork button, then push a branch on your own fork of the repo and then make a pull request to this repository again, this is how it works on github ;-)

OMG... OK :-)
I Will do it today or tomorrow.

**Comment by nen777w** [comment]
@DeeJayMX , @s00500 Done: https://github.com/s00500/ESPUI/pull/80
