### ISSUE TITLE
error during compilation 

### ISSUE THREAD

**Issue by robademar** [s00500/ESPUI#7]
I've installed the library and pre-req libraries. When I compile the example I get the following messages:

Arduino:1.8.5 (Windows 10), Scheda:"ESP32 Dev Module, QIO, 80MHz, 4MB (32Mb), 921600, None"

ATTENZIONE: la libreria FS dichiara di funzionare sulle architetture (esp32) e potrebbe non essere compatibile con la tua scheda che utilizza l'architettura (esp2)
ATTENZIONE: la libreria SPIFFS dichiara di funzionare sulle architetture (esp32) e potrebbe non essere compatibile con la tua scheda che utilizza l'architettura (esp2)
ATTENZIONE: la libreria WiFi dichiara di funzionare sulle architetture (esp32) e potrebbe non essere compatibile con la tua scheda che utilizza l'architettura (esp2)
C:\Users\roberto\Documents\arduino librerie\libraries\ESPUI\src\ESPUI.cpp: In function 'void onWsEvent(AsyncWebSocket*, AsyncWebSocketClient*, AwsEventType, void*, uint8_t*, size_t)':

C:\Users\roberto\Documents\arduino librerie\libraries\ESPUI\src\ESPUI.cpp:177:10: error: enumeration value 'WS_EVT_PONG' not handled in switch [-Werror=switch]

   switch (type) {

          ^

C:\Users\roberto\Documents\arduino librerie\libraries\ESPUI\src\ESPUI.cpp:177:10: error: enumeration value 'WS_EVT_ERROR' not handled in switch [-Werror=switch]

cc1plus.exe: some warnings being treated as errors

exit status 1
Errore durante la compilazione per la scheda ESP32 Dev Module.

Questo report potrebbe essere più ricco di informazioni abilitando l'opzione
"Mostra un output dettagliato durante la compilazione"
in "File -> Impostazioni"
+++++++++++++++++++++++
any suggestion?  thanks

**Comment by s00500** [comment]
what version of ESPAsyncWebserver are you using?

**Comment by robademar** [comment]
ESPAsyncWebserver 1.1.0  just downloaded tonight from git Giovanni Roberto Mariani 

    Il Martedì 6 Febbraio 2018 20:55, Lukas Bachschwell <notifications@github.com> ha scritto:
 

 what version of ESPAsyncWebserver are you using?—

**Comment by robademar** [comment]
ESPAsyncWebserver 1.1.0  just downloaded tonight from git

**Comment by per1234** [comment]
Note that the ESP32 [platform.txt](https://github.com/espressif/arduino-esp32/blob/master/platform.txt#L17-L21) sets the `--Werror=all` flag for the Arduino IDE's "More" and "All" warning levels (File > Preferences > Compiler warnings:). This means that you will not encounter this error with compiler warnings set to "None" or "Default".

Also possibly making it difficult to reproduce is that the Arduino IDE caches compiled libraries so if you have previously successfully compiled at a lower warning level you can then successfully compile at the higher warning level that would cause error on a fresh compile. You can clear the cache by switching boards or restarting the Arduino IDE.

**Comment by robademar** [comment]
Thanks tomorrow morning I will try 


Inviato da Yahoo Mail per iPhone


Il martedì, febbraio 6, 2018, 11:16 PM, per1234 <notifications@github.com> ha scritto:


Note that the ESP32 platform.txt sets the --Werror=all flag for the Arduino IDE's "More" and "All" warning levels (File > Preferences > Compiler warnings:). This means that you will not encounter this error with compiler warnings set to "None" or "Default".

Also possibly making it difficult to reproduce is that the Arduino IDE caches compiled libraries so if you have previously successfully compiled at a lower warning level you can then successfully compile at the higher warning level that would cause error on a fresh compile. You can clear the cache by switching boards or restarting the Arduino IDE.

**Comment by robademar** [comment]
I changed platform.txt as follows and it works now. Many thanks again for your prompt help.

compiler.warning_flags=-w
compiler.warning_flags.none=-w
compiler.warning_flags.default=
compiler.warning_flags.more=-Wall -Werror=none
compiler.warning_flags.all=-Wall  -Wextra

**Comment by s00500** [comment]
Tested it again, thanks @per1234 , Closing
