### ISSUE TITLE
How to turn off default sending data to Serial?

### ISSUE THREAD

**Issue by mafckz** [s00500/ESPUI#71]
I need to use hardware Serial in other task. 
And after commenting all lines with Serial.print in example gui.ino, the data still received in Serial Monitor.
Is it possible to turn off default sending data to hardware Serial?

**Comment by nen777w** [comment]
ESPUI.setVerbosity(Quiet); ?

**Comment by s00500** [comment]
That looks like the answer you need, can you confirm ?

**Comment by mafckz** [comment]
Yes.
Thanks a lot!
