### ISSUE TITLE
Different element sizes

### ISSUE THREAD

**Issue by SE232** [s00500/ESPUI#73]
I use the ESPUI as UI for my smart home devices. Depanding on the device there are a lots of items
up to 20+ on some tabs - to fill arrays in my software. 
Due to the (defined) element sizes, the screen is very soon filled and I need to scroll down 
Need to admit: I have no idea of web design, css... at all - so ESPUI is made for me :-)

It would be nice to have different sets of items in different sizes. They could by used like the Win10 blocks UI.
Switching between them could by implemented as a function call etc. before ESPUI.addControl. 
This could keep existing project using ESPUI compatible.

Alternative I need to learn more about CSS etc... 
This would allow to change the UI of  elements in generell (but is still not that flexible). A little help what I need to look for would be greatly appreciated !

**Comment by s00500** [comment]
Although I understand, I would really advise youz to not use ESPUI in such a scenario, Homeassistant or other alternatives can be used and provide a lot more powerfull features for UI, automations and security...
