### ISSUE TITLE
Shut down the UI

### ISSUE THREAD

**Issue by UpperAlex** [s00500/ESPUI#78]
I have two servers in my use case. Both should run on port 80 (not at the same time). My problem is, that I can not find a way to shut down the ESPUI without crashing the running program. 

It would be great to have an exit method to call, that closes everything without crashing. So I could start the other server again.

Alternatives that i can think of are in need of persisting flags, which would generate possibly a clash with another library.

**Comment by s00500** [comment]
ok so theoretically you chould be able to access the server instance directly... and then call the end() method on it....
https://github.com/me-no-dev/ESPAsyncWebServer/blob/9a5be71920c7be3c8d381b9d0beb0f7f08511b17/src/WebServer.cpp#L87

Make sure your ESPAsyncWebserver is up to date

ESPUI.server->reset(); // Remove all handlers and writers
ESPUI.server->end();

**Comment by s00500** [comment]
@UpperAlex did you test this solution ?

**Comment by s00500** [comment]
@UpperAlex ?

**Comment by Sylvio84** [comment]
Hi,

I want EspUI to be activated only when the WiFi is in access point mode.
So I want to shutdown it when the WiFi is connected.

server property is private so we can't access it to reset or end.

Is there a way to do that ? Thanks a lot
