### ISSUE TITLE
Min/Max Value for Number control in Tabbed mode control

### ISSUE THREAD

**Issue by DeeJayMX** [s00500/ESPUI#79]
How can I put Min and Max Value for number control in tabbed mode ?
is it possible ?

**Comment by DeeJayMX** [comment]
and no arrow to increment or decrement numbers

**Comment by DeeJayMX** [comment]
Anyone ?

**Comment by s00500** [comment]
To quote the main readme:

> The numberinput can be used to directly input numbers to your program. You can enter a Value into it and when you are done with your change it is sent to the ESP.
> 
> A number box needs to have a min and a max value. To set it up just use:
> 
> ESPUI.number("Numbertest", &numberCall, ControlColor::Alizarin, 5, 0, 10);

Currently there is no way to add any arrow controlls

**Comment by DeeJayMX** [comment]
I read the main readme,
I was talking about "tabbed mode", not standard ESPUI mode

**Comment by s00500** [comment]
This is done in the same fashion like the select options

```
  uint16_t numberbox = ESPUI.addControl(ControlType::Number, "Label", String(5), ControlColor::None, Control::noParent, &callback);
  ESPUI.addControl(ControlType::Min, "Label", String(1), ControlColor::None, numberbox);
  ESPUI.addControl(ControlType::Max, "Label", String(10), ControlColor::None, numberbox);
```

You can check how the Library is doing the same thing internally here: 
https://github.com/s00500/ESPUI/blob/master/src/ESPUI.cpp#L443

**Comment by DeeJayMX** [comment]
Great ! 👍

**Comment by az-z** [comment]
@DeeJayMX / @s00500 ,
sorry, but i seemed to be missing smth. here is my code :
`	//Under Tab1
	wifi_control = ESPUI.addControl( ControlType::Text, "Wifi SSID:", config.ssid, ControlColor::Alizarin, tab1, &textCallBack );
	//I need min/max length for the SSId
	ESPUI.addControl(ControlType::Min, "Wifi SSID:", String(2), ControlColor::None, wifi_control);
	ESPUI.addControl(ControlType::Max, "Wifi SSID:", String(5), ControlColor::None, wifi_control);
