### ISSUE TITLE
ESPUI.addControl vs ESPUI.number and min/max values

### ISSUE THREAD

**Issue by az-z** [s00500/ESPUI#82]
**Describe the bug**
1. I'm not sure this is a bug. I suspect it is my lack of understanding.

 "addControl" function doesn't seem to have the default,min, max parameters as ".number" has.

How do i add the number control with the def, min/max?

**To Reproduce**
ESPUI.addControl( ControlType::Number, "Sampling Frequency (min):", "60", ControlColor::Alizarin, tab2, &numberCall, **60, 60, 600 )**;
vs
ESPUI.number("Numbertest", &numberCall, ControlColor::Alizarin, **5, 0, 10)**;

**Expected behavior**
need to have default,min/max parameters with "number" control.

**Comment by DeeJayMX** [comment]
Check that
https://github.com/s00500/ESPUI/issues/79#issuecomment-643675938

**Comment by s00500** [comment]
@DeeJayMX thanks =D
