### ISSUE TITLE
order of controls

### ISSUE THREAD

**Issue by az-z** [s00500/ESPUI#85]
is there a way to control the order of the appearance of controls? 
e.g. i want to have tabs _above_ a button. But now i always get a button _above_ a tab, even though in the code tabs are defined first.
```
uint16_t tab1 = ESPUI.addControl( ControlType::Tab, "Settings 1", "WIFI" );
	uint16_t tab2 = ESPUI.addControl( ControlType::Tab, "Settings 2", "Sensors" );
	uint16_t tab3 = ESPUI.addControl( ControlType::Tab, "Settings 3", "Light" );
		//Under Tab1
	wifi_control = ESPUI.addControl( ControlType::Text, "Wifi SSID:", config.ssid, ControlColor::Alizarin, tab1, &textCallBack );
	
```
and down lower in the file :

`
	button1 = ESPUI.addControl( ControlType::Button, "", "Apply", ControlColor::Peterriver,Control::noParent, &buttonCallback );
`

**Comment by s00500** [comment]
I don't really understand the issue here, can you post a screenshot of this behaviour ?

**Comment by az-z** [comment]
> I don't really understand the issue here, can you post a screenshot of this behaviour ?

![image](https://user-images.githubusercontent.com/5010397/86056023-c41f4d80-ba2a-11ea-9d7a-1aa30b94e9c3.png)

**Comment by az-z** [comment]
i found the answer, though it doesn't solve the problem.
In the read me it says :
```

 ### Using Tabs

![tabs](https://github.com/s00500/ESPUI/blob/master/docs/ui_tabs.png)

Tabs can be used to organize your widgets in pages. Check the tabbedGui example.
Tabs can be created using the generic functions like so:
`ESPUI.addControl( ControlType::Tab, "Settings 1", "Settings 1" );`

Then all widgets for the tab need to be added to it by specifying the tab as the parrent (widgets not added to a tab will be shown above the tab selctor)

`ESPUI.addControl( ControlType::Text, "Text Title:", "a Text Field", ControlColor::Alizarin, tab1, &textCall );`

```


is there a way to move the button below the tabs ? :)

**Comment by s00500** [comment]
In your upper code you use Control::noParent, this is clearly wrong and should be the tabid

**Comment by az-z** [comment]
I understand "parent" as the control will be on one of the tabs, no?
I want to have the button outside (and below) the entire tab control...

**Comment by s00500** [comment]
No, that is currently not possible as it is also confusing in my opinion

**Comment by az-z** [comment]
What controls the order of elements (buttons, tabs, labels) on the page?
Having a button above the tab group is weird.

**Comment by s00500** [comment]
controls without a parent always are rendered above the tab bar as of right now
