### ISSUE TITLE
Use LittleFS instead of deprecated SPIFFS

### ISSUE THREAD

**Issue by bastiengrignon** [s00500/ESPUI#86]
**Is your feature request related to a problem? Please describe.**
Since `SIFFS` is deprecated it won't be used and remove in a few time

**Describe the solution you'd like**
What could be interesting is to change `SPIFFS` to the up-to-date component `LittleFS` in your library. 
It's important to keep external libraries used in your project up-to-date.

**Comment by s00500** [comment]
From looking through here: https://github.com/esp8266/Arduino/pull/7263/files
did I understand it correctly that there is no change in API at all ? so that would be simple todo, you could of course also submit a PR for the requested changes

**Comment by bastiengrignon** [comment]
Yes it's a simple name changing and maybe an include to add. 
I will submit a PR.

**Comment by s00500** [comment]
merged, I will release in 1 week or so
