### ISSUE TITLE
Default value for "select control"

### ISSUE THREAD

**Issue by az-z** [s00500/ESPUI#87]
**Describe the bug**
the value of the select control is "0" despite having assigned selection on the web element.
**To Reproduce**
```
	//under tab3
	time_schema = ESPUI.addControl( ControlType::Select, "Time Schema:"	, "", 	ControlColor::Turquoise, tab3, &selectCallback );
//	uint16_t select1 = ESPUI.addControl( ControlType::Select, "Select:", "", ControlColor::Alizarin, tab1, &selectExample );
	ESPUI.addControl( ControlType::Option, "18/8", "18", ControlColor::Alizarin, time_schema );
	ESPUI.addControl( ControlType::Option, "8/8", "8", ControlColor::Alizarin, time_schema );

```

![image](https://user-images.githubusercontent.com/5010397/86056445-77884200-ba2b-11ea-93e7-66c5964b5d7d.png)

when i click "apply" button the callback returns "0" for this element. It should return "18".

**Comment by s00500** [comment]
What apply button are you refering to ? The element only sends state back to the ESP on a change event... so something like this is expected but veru much depended of the rest of your code, how did you implement the apply button ?

**Comment by ericBcreator** [comment]
You have the default value for the control set to "" so it defaults to 0 but when the control initializes it does not call the callback function until you select another option from the list.
So just set a default value for the variable set by the callback function, 18 for the corresponding selection 0 (18/8 in the list).
Best practice to always set default values.
