### ISSUE TITLE
Callback functionality for tab-selection/switch

### ISSUE THREAD

**Issue by senspix** [s00500/ESPUI#90]
Hi,

What about a callback for tab-switches (backend)?

Instead of 
	settingsTab =  ESPUI.addControl(ControlType::Tab, "Settings", "settings");
we'd have
	settingsTab =  ESPUI.addControl(ControlType::Tab, "Settings", "settings", tabSwitchCallbackFunction);
with

void tabSwitchCallbackFunction(Control *sender, int value) {
	int whichOne = sender->id;

etc

It would be easier to update display values on the tab that's switched __to__

I might have missed something (or not understood) and the functionality might already be there (I'm not a js-programmer...)

**Comment by s00500** [comment]
Interesting Idea, but I will not have the time to implement it, so if anyone wants to go forward with a pr I will be happy to assist

**Comment by ericBcreator** [comment]
Javascript is not my expertise but this will be a nice feature which can benefit my project(s) as well, so I'll take a look at it.

**Comment by ericBcreator** [comment]
OK: implemented :-)

![espui-tabselected-callback](https://user-images.githubusercontent.com/44906396/94565589-b2d42000-0269-11eb-92d9-5a8bcfb6b7b7.jpg)

As I haven't collaborated on Github before: I guess the next step for me would be to open a pull request and post my changes, right? I'll look into that.

**Comment by senspix** [comment]
Great! Can I try it out?

**Comment by ericBcreator** [comment]
Sure, it however seems I can't create a new branch or fork to add the code
(or am I missing something over here)?
You can send me a message at ericbcreator dot gmail dot com so I can send
you the files directly to test.

**Comment by s00500** [comment]
you should be able to fork this repository, then push the changes to your fork and then create a pull request

**Comment by ericBcreator** [comment]
OK, the fork button was what I missed, just created the pr.

**Comment by senspix** [comment]
Great!
Manual installation from git is needed until PlatformIO discovers that there's a new realest
