### ISSUE TITLE
Suggestion: minimum height of a control?

### ISSUE THREAD

**Issue by ericBcreator** [s00500/ESPUI#93]
I use the ESPUI mostly on a PC in 2 column mode. A minor issue is that the number, button, slider and option list controls don't have the same height so on some rows (when the 1st control is heigher than the 2nd), the next row displays just one control, on the right side.

I solved this by editing the style.css file by adding `min-height: 100px;` to the .card { } definition and removing `	.card-slider {
		padding-bottom: 10px;
	}
`
Maybe a thought to implement in a next version.

Another suggestion: in the .label { } definition I changed the line-height to 1.3, it makes reading multiline labels easier.

**Comment by s00500** [comment]
Sounds good to me, can you provide some screenshots of the difference ?

**Comment by ericBcreator** [comment]
Sure, here are 2 composite screenshots (with 2 tabs of my clock project next to each other).

This is the current css style, note how some controls get pushed to the 2nd column because of height differences of the 2 previous controls:

![espui-no-min-height-1](https://user-images.githubusercontent.com/44906396/93876106-8737bf80-fcd6-11ea-9cb5-29b0447ddc7e.jpg)

This one is with my 2 small changes, every row now displays 2 controls:

![espui-min-height-100px-1](https://user-images.githubusercontent.com/44906396/93876118-8b63dd00-fcd6-11ea-9003-794d560d2a9b.jpg)

**Comment by s00500** [comment]
Alright, this looks like a nice improvement,
do you want to submit a PR or shall I make the change ?

**Comment by ericBcreator** [comment]
It woud be great if you made the change, it’s just a minor improvement but useful in some scenarios nonetheless.

**Comment by s00500** [comment]
Alright, I added the changes on master, thanks =D

**Comment by ericBcreator** [comment]
Great, thanks as well!
