### ISSUE TITLE
ESPUI-master\src/ESPUI.h:14:22: fatal error: LittleFS.h: No such file or directory

### ISSUE THREAD

**Issue by misujr** [s00500/ESPUI#94]
**Describe the bug**
On ESP32 WROOM-32D, Using Arfduino IDE 1.8.12  if I try to upload the example "prepareFilesystem" on MacOS Catalina or Win10 I get the following error : ESPUI-master\src/ESPUI.h:14:22: fatal error: LittleFS.h: No such file or directory

**To Reproduce**
1. Board selected : Wemos D1 mini ESP32
2. Install ESPUI from Adruino Library manager
4. Open the prepareFilesystem example
5. Upload

**Expected behavior**
Compile and upload

**Desktop :**
 - OS: MacOs Catalina and Windows 10 Pro build 10941

**Additional context**
I have found LittleFS.h in the core for ESP8266 and if I try to run any of the examples on ESP8266 they work flawlessly. Is there a way in which I can get them to run on ESP32 ? I am not a dev so I might have missed some very easy step and I am eager to learn what I can do to fix this :-) .

**Comment by s00500** [comment]
ok, so you could use the in memory version, without prepareFilesystem, that is the easy workaround.

Otherwise this issue is my screw up on not checking good enough on the littleFS pullrequest, as littleFS does not exist in the ESP32 Arduino core

So this needs fixing. I have added fixes on the branch fix_littlefs_esp32, could you test this branch ?

**Comment by misujr** [comment]
I have just downloaded and tested the library in the branch fix_littlefs_esp32 and it comes up with a bunch of errors this time ( yesterday on the production branch I was getting just one error) though all of them are realted to littleFS. I will post here the error messages log from Arduino IDE on Windows but I have tested and got same results under MacOs Catalina also .

One thing about loading from Progmem, actually yesterday and today my first try was using progmem ( ESPUI.begin() ) but I have tested with the same error results ESPUI.prepareFileSystem() . 

I am hoping it is not only me not being able to compile hence I used 2 computers with different OS's to try and check the problem is not the user in front of my keyboard :-) . 


Arduino: 1.8.12 (Windows 10), Board: "WEMOS D1 MINI ESP32, 80MHz, Default, 240MHz (WiFi/BT), 921600"

_C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp: In function 'void listDir(const char*, uint8_t)':

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp:28:15: error: 'SPIFFS' was not declared in this scope

   File root = SPIFFS.open(dirname);

               ^

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp: In member function 'void ESPUIClass::list()':

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp:104:8: error: 'LittleFS' was not declared in this scope

   if (!LittleFS.begin())

        ^

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp:113:18: error: 'SPIFFS' was not declared in this scope

   Serial.println(SPIFFS.totalBytes());

                  ^

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp: In function 'void deleteFile(const char*)':

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp:130:18: error: 'LittleFS' was not declared in this scope

     Serial.print(LittleFS.exists(path));

                  ^

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp:133:8: error: 'LittleFS' was not declared in this scope

   if (!LittleFS.exists(path))

        ^

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp:148:7: error: 'LittleFS' was not declared in this scope

   if (LittleFS.remove(path))

       ^

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp: In function 'void writeFile(const char*, const char*)':

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp:171:15: error: 'LittleFS' was not declared in this scope

   File file = LittleFS.open(path, FILE_WRITE);

               ^

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp: In member function 'void ESPUIClass::prepareFileSystem()':

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp:233:3: error: 'SPIFFS' was not declared in this scope

   SPIFFS.format();

   ^

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp: In member function 'void ESPUIClass::beginSPIFFS(const char*, const char*, const char*)':

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp:921:8: error: 'LittleFS' was not declared in this scope

   if (!LittleFS.begin())

        ^

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp:936:8: error: 'LittleFS' was not declared in this scope

   if (!LittleFS.exists("/index.htm"))

        ^

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp:955:30: error: 'LittleFS' was not declared in this scope

     server->serveStatic("/", LittleFS, "/").setDefaultFile("index.htm").setAuthentication(username, password);

                              ^

C:\...\Documents\Arduino\libraries\ESPUI-fix_littlefs_esp32\src\ESPUI.cpp:959:30: error: 'LittleFS' was not declared in this scope

     server->serveStatic("/", LittleFS, "/").setDefaultFile("index.htm");

                              ^

Multiple libraries were found for "WiFiUdp.h"
 Used: C:\...\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.4\libraries\WiFi
 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
Error compiling for board WEMOS D1 MINI ESP32.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences._

**Comment by misujr** [comment]
Using PlatformIO I have managed to compile and upload the gui example code. 
I will try to work in PlatformIO to advance my project idea while giving you support to test the Arduino IDE fucntionality as honestly I am much more familiar with ArduinoIDE :-D  .

**Comment by s00500** [comment]
Alright, please retest with the latest changes, I think I have replaced all LittleFS usages now

**Comment by misujr** [comment]
Sorry for responding with a bit of delay . 
Main branch 👍 
On windows now I only get 1 error message about LittleFS : 
C:\...\Arduino\libraries\ESPUI\src/ESPUI.h:14:22: fatal error: LittleFS.h: No such file or directory
LittleFS fix Branch :
MacOS -> Compiles and works perfectly !
Windows -> Compiles and works perfectly !

Thank you very  very very much fopr fixing this and Congratulations for such an amazing library !!!

BR,
Misujr
