### ISSUE TITLE
Occasional bug: the first control (control ID 0) displays 0 instead of the defined text

### ISSUE THREAD

**Issue by ericBcreator** [s00500/ESPUI#95]
Here is a screenshot with the bug on the left and the correct text on the right. The 1st initialized control tab 1 displays 0 instead  of the text 'Main settings':

![espui-control0-0](https://user-images.githubusercontent.com/44906396/94332229-856e4480-ffd3-11ea-965d-936a8d1fa7dd.jpg)

I tried adding the tabs after the 4 controls above them to check if it was related to the tabs but that didn't not solve it, instead the 'OK' text on the first control 'Save to memory' button changed to 0.
Oddly, the issue occurred with some of my Wemos D1 mini's and some not, I haven't been able to pinpoint the exact cause.
I had the issue with all major browsers on Windows 10 and also on iOS 13.7 and Mac 10.15.5.

What solved the issue for me on all ESP8266s was editing ESPUI.cpp and starting the idCounter with 1 instead of 0:

`uint16_t Control::idCounter = 1;`

**Comment by s00500** [comment]
Hm... would be interesting to debug that further.... can you add your code here ? and also try to capture the JSON object sent to the browser, it should be logged on the browser control or if you set VerboseJSON loglevel on the ESPs console

**Comment by ericBcreator** [comment]
OK, I reloaded that version of my clock project on the same Wemos D1 mini 2 times, the same source code, no changes.
The 1st upload is on the left with the default ESPUI.cpp setting `uint16_t Control::idCounter = 0`, the 2nd is on the right with `uint16_t Control::idCounter = 1`:

![espui-control0-1-ok](https://user-images.githubusercontent.com/44906396/94370208-f2c2c800-00ee-11eb-84b7-5a61bc9157c3.jpg)

Interestingly enough, this time I got a 1 instead of a 0 on the 1st tab. The 2nd upload correctly displays 'Main settings'.
I can upload the entire code here if you like but the project is quite elaborate (a couple of Ks of lines, over a dozen files, the project page is [here](https://www.hackster.io/ericBcreator/programmable-multi-alarm-clock-with-web-interface-75dc6a)) so here is just the first part of the ESPUI code:

```
  WiFi.softAPConfig(UI_apIP, UI_apIP, IPAddress(255, 255, 255, 0));
  #ifdef ESP32
    WiFi.setHostname(UI_ssid_ca);
  #else
    WiFi.hostname(UI_ssid_ca);
  #endif
  WiFi.softAP(UI_ssid, UI_password, UI_channel);
  UI_dnsServer.start (UI_DNS_PORT, "*", UI_apIP);

  ESPUI.setVerbosity(Verbosity::VerboseJSON);

  const char * UI_msg_tab_general         = "Main settings";
  const char * UI_msg_tab_alarms          = "Alarms";

  uint16_t UI_tabG = ESPUI.addControl(ControlType::Tab, UI_msg_tab_general, UI_msg_tab_general);
  uint16_t UI_tabA = ESPUI.addControl(ControlType::Tab, UI_msg_tab_alarms, UI_msg_tab_alarms);

```

And here is the JSON log (first part) for the 1st upload:

```
Connected: 1
{"type":200,"sliderContinuous":false,"controls":[{"type":0,"label":"  eBclock-study-3AD"},{"id":"0","type":11,"label":"Main settings","value":"1","color":0},{"id":"1","type":11,"label":"Alarms","value":"Alarms","color":0},{"id":"2","type":3,"label":"Save to memory","value":"OK","color":1}
```

And the 2nd:

```
Connected: 1
{"type":200,"sliderContinuous":false,"controls":[{"type":0,"label":"  eBclock-study-3AD"},{"id":"1","type":11,"label":"Main settings","value":"Main settings","color":0},{"id":"2","type":11,"label":"Alarms","value":"Alarms","color":0},{"id":"3","type":3,"label":"Save to memory","value":"OK","color":1}
```

You'll notice the value of control / ID 0 gets 'reset' to 1 for the 1st and remains 'Main settings' for the 2nd upload when starting with control / ID 1.

Note: I also uploaded the 1st compilation to another Wemos D1 mini and it displayed 'Main settings' correctly, no problem...strange.

**Comment by s00500** [comment]
It is a quite strange issue, but I guess there is no harm in just changing it, thanks for the investigation :-)

**Comment by s00500** [comment]
Supernice alarm clock btw =D, just checked the project

**Comment by ericBcreator** [comment]
Thanks! And a strange issue indeed. But an easy solution. Sometimes logic makes little sense.

BTW: the alarm clock project kind of escalated, I wouldn't have anticipated K's of code for a 'simple' clock project.
