### ISSUE TITLE
Only 7 ControlType::Option displayed.

### ISSUE THREAD

**Issue by nen777w** [s00500/ESPUI#99]
I try to display 21 ControlType::Option in ControlType::Select control.

ESPUI.addControl(ControlType::Option, "test1", "test1", ControlColor::Emerald, web_ui::get().cbb_phrases);
ESPUI.addControl(ControlType::Option, "test2", "test2", ControlColor::Emerald, web_ui::get().cbb_phrases);
ESPUI.addControl(ControlType::Option, "test3", "test3", ControlColor::Emerald, web_ui::get().cbb_phrases);
...
ESPUI.addControl(ControlType::Option, "test21", "test21", ControlColor::Emerald, web_ui::get().cbb_phrases);

But only 7 is displayed.
Why?

**Comment by s00500** [comment]
Can you add the rest of your sketch here as well ? and add what processor you are using ? are there any errors on the browser console ?

**Comment by nen777w** [comment]
Unfortunately, the rest part of the sketch is too huge to paste it here.

I use :
platform = espressif32
board = esp32doit-devkit-v1

In web browser console:

DevTools failed to load SourceMap: Could not load content for chrome-extension://dbfipcjecamggjfabeaclacjoohfjhhn/dist/js/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
content.js:69 microParse prop =>> 0 e {price: "0", title: "Control", description: "", img: "", img_all: Array(0), …}
content.js:69 microParse ldJson =>> 0 e {price: "0", title: "Control", description: "", img: "", img_all: Array(0), …}
content.js:69 microParse metaOG =>> 0 e {price: "0", title: "Control", description: "", img: "", img_all: Array(0), …}
controls.js:10 websock open

**Comment by s00500** [comment]
ok that makes it almost impossible to debug... can you post it in a gist or a pasteboard ? like paste.lbsfilm.at

**Comment by nen777w** [comment]
> ok that makes it almost impossible to debug... can you post it in a gist or a pasteboard ? like paste.lbsfilm.at

It's a medium-size my own home project intended for the control of the door lock. (Here is some details if interesting: https://www.facebook.com/codijy/posts/2757615851192673?__cft__[0]=AZUO9uATfVhIX45q4rU2_-3uTVBhJgic4_mZ6Qir44g409az-dLSbpBueMmT-rrx42KpESZms_GZpuOUzE2U7W24xBtYqdX1r0gRlo05T3myIDLOu76RCYDoMKSkgNv-sBw&__tn__=%2CO%2CP-R)

If you want I can send all sources code to you, or I can debug myself.
The problem with debugging is that I already mounted it on the door, and for the updates, I flash it over the air (OTA).
As far I know espota protocol does not support monitor port and probably I will need to plug a JTAG.
So for debugging I need to demount it or purchase a new ESP32 module and debugging it there.

**Comment by nen777w** [comment]
The problem was solved. Just increase the ESPUI.jsonInitialDocumentSize.

**Comment by iangray001** [comment]
This should be fixed with a recent update so `jsonInitialDocumentSize` doesn't matter any more.
